### ISSUE TITLE
[Question] about xmp_event.fxp fxt

### ISSUE THREAD

**Issue by knight-ryu12** [libxmp/libxmp#141]
what's those value supposed to return?
Is it effect byte or character used…?

**Comment by NoSuck** [comment]
They are variables and do not “return” anything.  Have you checked the documentation for `xmp_inject_event`?

**Comment by knight-ryu12** [comment]
I did and making questions, sorry for misusing terminology.

More like what "kind of value that represents effect"…

2019年6月18日(火) 10:21 NoSuck <notifications@github.com>:

**Comment by knight-ryu12** [comment]
To be honest, that should deserve the document and example C code
