### ISSUE TITLE
File "WCTIT.MOD" uses Fxx for BPM but it is detected as a Noisetracker mod

### ISSUE THREAD

**Issue by AliceLR** [libxmp/libxmp#144]
A game with this MOD was submitted to us today and libxmp plays it much slower than expected. From the first row of the first pattern it's pretty clearly trying to use F for both speed and BPM, but libxmp detects it as a Noisetracker MOD and enables QUIRK_NOBPM, so the BPM value is read as a speed instead. I've tested it with MPT/libmodplug, OpenMPT, and Protracker clone so far and it works correctly in all three as far as I can tell.

```
Loading WCTIT.MOD (1 of 1)
Module name  : Wall Crusher Theme
Module type  : Noisetracker M.K.
Module length: 8 patterns
Patterns     : 6
Instruments  : 31
Samples      : 31
Channels     : 4 [ 4 b b 4 ]
Duration     : 14min34s (main sequence)
               4min36s (sequence 1 at position 01)
```

[WCTIT.zip](https://github.com/cmatsuoka/libxmp/files/3408014/WCTIT.zip)

**Comment by AliceLR** [comment]
This isn't the cause of this particular file's problem, but I found a related issue where `m->size` isn't set in `xmp_load_module`. This might cause the FlexTrax, Mod's Grave, and Protracker song file checks to incorrectly fail.

I think in the case of this file the problem might just be that `get_tracker_id` is a little too quick to decide that files are from Noisetracker. I don't know enough about the specifics of particular trackers so someone else might have to look at this. I don't know what the actual tracker used for this file is and the original author is not likely to provide a useful response.

**Comment by AliceLR** [comment]
Here's a patch that "fixes" detection for this particular MOD. I think it could be improved, though (e.g. it could be merged into the existing NoiseTracker effects check).

```patch
diff --git a/src/loaders/mod_load.c b/src/loaders/mod_load.c
index 070d584f..707c9691 100644
--- a/src/loaders/mod_load.c
+++ b/src/loaders/mod_load.c
@@ -595,6 +595,8 @@ skip_test:
 
     for (i = 0; i < mod->pat; i++) {
 	long pos;
+	int has_speed = 0;
+	int has_bpm = 0;
 
 	if (libxmp_alloc_pattern_tracks(mod, i, 64) < 0)
 	    return -1;
@@ -607,6 +609,11 @@ skip_test:
 	for (j = 0; j < (64 * mod->chn); j++) {
             int period;
 
+	    if (!(j % mod->chn)) {
+		has_speed = 0;
+		has_bpm = 0;
+	    }
+
 	    event = &EVENT(i, j % mod->chn, j / mod->chn);
 	    hio_read(mod_event, 1, 4, f);
 
@@ -624,6 +631,23 @@ skip_test:
 		    tracker_id = TRACKER_UNKNOWN;
 		}
 	    }
+
+	    /* Noisetracker doesn't support Fxx used for BPM, so if there's a row
+	     * where this occurs unambiguously, it's probably not Noisetracker. */
+	    if (tracker_id == TRACKER_PROBABLY_NOISETRACKER || tracker_id == TRACKER_NOISETRACKER) {
+		unsigned char fxt = LSN(mod_event[2]);
+		unsigned char fxp = mod_event[3];
+
+		if (fxt == 0xF) {
+		    if (fxp <= 0x1F)
+			has_speed = 1;
+		    else
+			has_bpm = 1;
+
+		    if (has_speed && has_bpm)
+			tracker_id = TRACKER_UNKNOWN;
+		}
+	    }
 	}
 
         if (out_of_range) {
```

More about this MOD: while WCTIT.MOD doesn't have any empty samples with volume set, two other MODs by the same author packaged with the same game are 6CHN and do have empty samples with volume. Considering this and that these were all made recently (the copyright date in the MOD is a lie), I think OpenMPT might be the source of both.

The reasons `get_tracker_id` detects this as a NoiseTracker MOD are:

1) [The restart byte of this MOD is set to 0](https://github.com/cmatsuoka/libxmp/blob/master/src/loaders/mod_load.c#L290). NoiseTracker, FastTracker, and OpenMPT all apparently support this, but this MOD is flagged as NoiseTracker here.

2) [A later check in the function](https://github.com/cmatsuoka/libxmp/blob/master/src/loaders/mod_load.c#L330) also relies solely on empty sample volume to decide between NoiseTracker and OpenMPT. This overrides the tracker ID chosen from the restart byte.

**Comment by NoSuck** [comment]
Thank you for the detective work.  I cannot help but wonder now if OpenMPT, after importing a MOD with zero-volume empty instruments, keeps said volume levels as-is.  Perhaps this MOD's author modified a pre-existing MOD (that was perhaps made with NoiseTracker or another non-OpenMPT tracker) with OpenMPT.

**Comment by AliceLR** [comment]
I think that's plausible. Without going too much into detail, the author of this MOD has shown a pattern of copying work and claiming it as their own.

I tested resaving a different MOD with volume 0 empty instruments from OpenMPT and the empty instruments do still have a volume of 0. For whatever reason, adding `Fxx` for tempo to the particular MOD I tested with does work as expected and I haven't figured out why yet.

**Comment by AliceLR** [comment]
Here's another older MOD that's been edited using OpenMPT with the same problem when played by xmp:

[CM_BOSS_v2.mod.zip](https://github.com/cmatsuoka/libxmp/files/4698927/CM_BOSS_v2.mod.zip)

**Comment by sagamusix** [comment]
I would keep CIA/VBlank timing detection completely separate from any other Noisetracker fingerprinting, in particular anything that can be achieved in any other tracker as well (the default volume OpenMPT or other trackers choose for empty sample slots is just a default; the user can still overwrite it with whatever value they like and as such it allows for false negatives).

**Comment by sezero** [comment]
This needs a bump I guess, since we have a similar situation in #505
