### ISSUE TITLE
Support for tempo/speed control

### ISSUE THREAD

**Issue by mmontag** [libxmp/libxmp#151]
Is there possibility of exposing a high-level speed control in the libxmp API?

In my project, I've accomplished this by injecting tempo commands:
https://github.com/mmontag/chip-player-js/blob/master/src/players/XMPPlayer.js#L169

This makes `current_time` from libxmp invalid, and requires a workaround like the following: 
https://github.com/mmontag/chip-player-js/commit/3b5209d4b1121f085c5b7190d1c4944891ad40ee#diff-937c8358718037516bb5c07797a8c0ff

You can see it working here (Speed slider is under Player Settings).
https://mmontag.github.io/chip-player-js/?q=drax&play=Modland%2FDrax%2Fbaked%20beams.xm

Would love to see this natively supported in the lib.

**Comment by mmontag** [comment]
Unfortunately my workaround is not very effective, and some songs start playing with the wrong tempo. 
@cmatsuoka - is support for global tempo/speed scaling on the roadmap? 
If not, is there a better workaround?

**Comment by NoSuck** [comment]
[xmp_inject_event](https://github.com/libxmp/libxmp/blob/master/docs/libxmp.rst#void-xmp-inject-event-xmp-context-c-int-chn-struct-xmp-event-event) covers this.  If you want to prevent a song from changing tempo after an injected event does, the underlying MOD file must be changed.

There is also `xmp_set_tempo_factor` (recently added).

**Comment by mmontag** [comment]
Thanks, `xmp_set_tempo_factor` looks like it would do the trick. Will give it a try!

**Comment by mmontag** [comment]
See https://github.com/libxmp/libxmp/commit/b1fb1ee84a1c28bdb5765cd7119e88aa68785511
