### ISSUE TITLE
Keyoff+Instrument change bug with xyce-dans_la_rue.xm

### ISSUE THREAD

**Issue by vlad54rus** [libxmp/libxmp#152]
Tried to play xyce-dans_la_rue.xm (https://modarchive.org/index.php?request=view_by_moduleid&query=172032) with latest Xmp For Android and encountered this issue.
When keyoff note paired with instrument change command, previous instrument starts playing again at full volume.
xyce-dans_la_rue.xm, patterns 0E, 0F, 16,17.

**Comment by sezero** [comment]
This doesn't sound like an Android-specific issue.
