### ISSUE TITLE
Build regression tests with Visual Studio in Windows

### ISSUE THREAD

**Issue by cmatsuoka** [libxmp/libxmp#222]
We should provide means to run regression tests for our WIndows build in Travis.

**Comment by AliceLR** [comment]
I added a Makefile.vc.in file in #331 and got the tests running with nmake so that's at least some progress here. There are a couple of issues: first, all_tests.c still requires GNU Make and the resulting Makefile.vc is a little verbose, so they still require some support from outside of MSVC (shouldn't be an issue for Travis-CI). Second, some of the tests were failing/crashing for me, and (assuming these can be reproduced elsewhere and aren't due to user error) should be resolved before adding Travis-CI tests:
```
test 185: test_api_test_module: at .\test_api_test_module.c:16: errno test module fail: **fail**
test 186: test_api_load_module: at .\test_api_load_module.c:20: errno code: **fail**
test 188: test_api_load_module_from_file:
test 189: test_api_test_module_from_file:
test 206: test_api_smix_load_sample: at .\test_api_smix_load_sample.c:32: errno: **fail**
```

**Comment by sezero** [comment]
> ```
> test 185: test_api_test_module: at .\test_api_test_module.c:16: errno test module fail: **fail**
> ```

This one is because errno not matching EISDIR: Because fopen()ing a
directory would actually succeed, xmp_load_module and xmp_test_module
manually set errno to EISDIR but not for MSVC, hence the test failure.
I suggest something like the following:
```diff
diff --git a/src/load.c b/src/load.c
index 9052849..ccc592a 100644
--- a/src/load.c
+++ b/src/load.c
@@ -336,6 +336,10 @@ static int test_module(struct xmp_test_info *info, HIO_HANDLE *h)
        return -XMP_ERROR_FORMAT;
 }
 
+#if defined(_MSC_VER)
+#define S_ISDIR(x) (((x)&_S_IFDIR) != 0)
+#endif
+
 int xmp_test_module(const char *path, struct xmp_test_info *info)
 {
        HIO_HANDLE *h;
@@ -348,12 +352,10 @@ int xmp_test_module(const char *path, struct xmp_test_info *info)
        if (stat(path, &st) < 0)
                return -XMP_ERROR_SYSTEM;
 
-#ifndef _MSC_VER
        if (S_ISDIR(st.st_mode)) {
                errno = EISDIR;
                return -XMP_ERROR_SYSTEM;
        }
-#endif
 
        if ((h = hio_open(path, "rb")) == NULL)
                return -XMP_ERROR_SYSTEM;
@@ -559,12 +561,10 @@ int xmp_load_module(xmp_context opaque, const char *path)
                return -XMP_ERROR_SYSTEM;
        }
 
-#ifndef _MSC_VER
        if (S_ISDIR(st.st_mode)) {
                errno = EISDIR;
                return -XMP_ERROR_SYSTEM;
        }
-#endif
 
        if ((h = hio_open(path, "rb")) == NULL) {
                return -XMP_ERROR_SYSTEM;
```

**Comment by sezero** [comment]
As for others, the issue is errno not matching `ENOENT`.
I did a quick `if (stat("nonexist",&st)<0) printf("%d\",errno);`
and built with cl.exe, it prints `2` for me which _is_ `ENOENT`.

**Comment by AliceLR** [comment]
The two crashes both occur in hio.c's `get_size` function when calling `ftell` on the user-provided `FILE *`, so those do seem to be user error on my part. Still not sure why libxmp.dll and the tests end up getting incompatible `FILE *`s.

**Comment by sezero** [comment]
Does https://github.com/libxmp/libxmp/issues/222#issuecomment-806178582 cure your EISDIR failures? If it does I can push it.

**Comment by AliceLR** [comment]
> Does [#222 (comment)](https://github.com/libxmp/libxmp/issues/222#issuecomment-806178582) cure your EISDIR failures? If it does I can push it.

Your patch does work (i.e. my MSVC test build detects when the input is a directory) but the test still fails in a similar way to the other two: when the test checks `errno` it is 0 instead of the expected value (maybe like my `FILE *` issue, libxmp.dll and the tests have a different `_errno()`?).

**Comment by sezero** [comment]
Does `/MD` in libxmp.dll cflags (and possibly `/MT` in test-dev cflags) change anything?
(shooting in the dark here..)

**Comment by AliceLR** [comment]
I think you're on the right track—I was suspicious that there wasn't a VC runtime DLL linked. Despite the documentation implying that `/MD` is for DLLs and `/MT` is for executables it seems that actually `/MD` forces linking to a VC runtime DLL and `/MT` pulls in a static runtime (not desired). With `/MD` added to both libxmp.dll and libxmp-tests.exe they seem to share the correct `FILE *` and `errno` now, but `test_api_load_module` crashes now for unknown reasons (will check into that...).

**Comment by AliceLR** [comment]
After replacing `creat` everything works fine now. I went ahead and opened a pull request with the fixes for those issues. Thanks for helping diagnose those bugs... this is pretty much the first time I've ever attempted to use MSVC.
