### ISSUE TITLE
OctaMED 8-channel mode timing is inaccurate.

### ISSUE THREAD

**Issue by AliceLR** [libxmp/libxmp#232]
xmp's OctaMED 8-channel mode tempos are inaccurate, and result in some strange playback issues with modules that rely on timing long samples with other notes.

[you got to let the music](https://modland.com/pub/modules/OctaMED%20MMD1/-%20unknown/you%20got%20to%20let%20the%20music.mmd1)
[stop chit !](https://modland.com/pub/modules/OctaMED%20MMD1/-%20unknown/stop%20chit%20!.mmd1)

The 8-channel tempo table used in xmp appears to have been created using the tempo conversion dialog in OctaMED SS 1.03c, which can only convert 8-channel mode tempos to tempo mode tempos (which are less accurate than BPMs). OpenMPT uses more accurate values that are identical to the BPM values generated by OctaMED SS 2/MED Soundstudio when importing 8-channel mode modules.

| Speed | xmp (approx. BPM)	| OctaMED SS 1.03c conversion	| [OpenMPT](https://github.com/OpenMPT/openmpt/commit/07c559e28f297b40df7816e864ca5ff34b910d6b)/OctaMED SS 2 import |
|-------|-----------------------|-------------------------------|--------------------------------|
| 1	| 47 (178.03)		| 1 → 47 → 177			| 179
| 2	| 43 (162.87)		| 2 → 43 → 162			| 164
| 3	| 40 (151.51)		| 3 → 40 → 151			| 152
| 4	| 37 (140.15)		| 4 → 37 → 140			| 141
| 5	| 35 (132.57)		| 5 → 35 → 132			| 131
| 6	| 32 (121.21)		| 6 → 32 → 121			| 123
| 7	| 30 (113.63)		| 7 → 30 → 113			| 116
| 8	| 29 (109.84)		| 8 → 29 → 109			| 110
| 9	| 27 (102.27)		| 9 → 27 → 102			| 104
| 10	| 26 (98.48)		| 10 → 26 → 98			| 99

To verify these, I tried timing BPMs with OctaMED 4 in an Amiga 1200 VM (PAL) using a module containing a single blank 64-line block and the OctaMED playback timer (probably not a particularly precise way to do this, oh well). I tried some of these again with an Amiga 4000 VM (PAL) and got similar results. Numbers in parentheses are the number of repeats and number of beats (4 lines) completed within the last repeat when I stopped playback.

| Speed	| Test 1		| Test 2		| Test 3		| Average BPM, rounded |
|-------|-----------------------|-----------------------|-----------------------|----------------------|
| 1	| 178 (11,2)		| 178 (11,2)		| 177.75 (11,1.75)	| 178
| 2	| 163 (10,3)		| 163 (10,3)		| 162.75 (10,2.75)	| 163
| 3	| 150.5 (9,6.5)		| 150.25 (9,6.25)	| 150.5 (9,6.5)		| 150
| 4	| 139.5 (8,11.5)	| 139.5 (8,11.5)	| 139.75 (8,11.75)	| 140
| 5	| 130 (8,2)		| 130.5 (8,2.5)		| 130.25 (8,2.25)	| 130
| 6	| 122 (7,10)		| 122.25 (7,10.25)	| 122 (7,10)		| 122
| 7	| 115 (7,3)		| 115 (7,3)		| 115.25 (7,3.25)	| 115
| 8	| 108.5 (6,12.5)	| 108.5 (6,12.5)	| 108.5 (6,12.5)	| 109
| 9	| 102.5 (6,6.5)		| 102.75 (6,6.75)	| 102.75 (6,6.75) 	| 103
| 10	| 97.5 (6,1.5)		| 97.5 (6,1.5)		| 97.5 (6,1.5)		| 98

From testing "you got to let the music.mmd1", which uses speed 7, the average BPM measured (115) is closer in playback duration but the SS 2 BPM (116) results in fewer sample synchronization bugs. Interestingly, dividing the measured BPMs by 7093790/7159090 results in something close to the equivalent SS 2 BPMs. So to be sure, I did the tests again with the same Amiga VM switched to NTSC:

| Speed	| Test 1		| Test 2		| Test 3		| Average BPM, rounded |
|-------|-----------------------|-----------------------|-----------------------|----------------------|
| 1	| 179.75 (11,3.75)	| 179 (11,3)		| 179.25 (11,3.25)	| 179
| 2	| 164.75 (10,4.75)	| 164.25 (10,4.25)	| 164.5 (10,4.5)	| 165
| 3	| 152 (9,8)		| 151.75 (9,7.75)	| 152 (9,8)		| 152
| 4	| 141 (8,13)		| 141 (8,13)		| 140.75 (8,12.75)	| 141
| 5	| 131.75 (8,3.75)	| 131.5 (8,3.5)		| 131.75 (8,3.75)	| 132
| 6	| 123.25 (7,11.25)	| 123.25 (7,11.25)	| 123 (7,11)		| 123
| 7	| 115.75 (7,3.75) 	| 116 (7,4)		| 116 (7,4)		| 116
| 8	| 109.5 (6,13.5)	| 109.5 (6,13.5)	| 109.5 (6,13.5)	| 110
| 9	| 103.5 (6,7.5)		| 104 (6,8)		| 103.75 (6,7.75)	| 104
| 10	| 98.5 (6,2.5)		| 98.75 (6,2.75)	| 98.5 (6,2.5)		| 99

NTSC and PAL definitely have different 8-channel mode timing (more different than regular timing anyway). This isn't really that surprising since 8-channel mode tempos are based on changing the size of the mix buffer. So, xmp should probably convert 8-channel mode timing to BPM mode and use the NTSC table values (more or less exactly the same as the OctaMED SS 2 conversions). MikMod also uses NTSC sample frequencies and should use the NTSC table. Since OpenMPT loads OctaMED samples at the PAL rate(?) the PAL values might be worth trying.

Some modules that use the various speeds:

| Speed	| Modules using this tempo |
|-------|--------------------------|
| 1	| privinv.mmd1, koala.mmd1
| 2	| go movin.mmd1
| 3	| tripper goes to raveland.mmd1, frequency confusion.mmd1
| 4	| to the house.mmd1
| 5	| starburst.mmd1, song of power.mmd1
| 6	| maria.mmd1, memories of anna.mmd1
| 7	| you got to let the music.mmd1, stop chit !.mmd1
| 8	| arligentia2.mmd1, depths of your dreams.mmd1
| 9	| secret of mana.mmd1, michael.mmd1
| 10	| anvil.mmd0, trend.mmd0, kinnunen 2.mmd0

Module duration measurements in samples recorded from stereo mix at 44100Hz. (OctaMED 4/PAL, OctaMED 4/NTSC, xmp with the table measured from PAL emulation, xmp with the table measured from NTSC emulation):

| Speed	| Module			| OctaMED (PAL)	| OctaMED (NTSC) | xmp (PAL table) | xmp (NTSC table) |
|-------|-------------------------------|---------------|----------------|-----------------|------------------|
| 1	| privinv.mmd1			| 15217152	| 15049317	| 15201893 (178)	| 15094272 (179)
| 2	| go movin.mmd1			| 18743808	| 18552805	| 18738789 (163)	| 18515301 (165)
| 3	| frequency confusion.mmd1	| 8467968	| 8378469	| 9494181(!) (150)	| 8378880 (152)
| 4	| to the house.mmd1		| 13853184	| 13703781	| 13812325(!) (140)	| 13708288 (141)
| 5	| song of power.mmd1		| 7717376	| 7621221	| 7734144 (130)		| 7604224 (132)
| 6	| memories of anna.mmd1		| 18310144	| 18118245	| 18335845 (122)	| 18193408 (123)
| 7	| you got to let the music.mmd1	| 4573952	| 4534501	| 4578917 (115)		| 4538213 (116)
| 8	| arligentia2.mmd1		| 8068224	| 7996773	| 8048421 (109)		| 7976960 (110)
| 9	| secret of mana.mmd1		| 1916928	| 1898853	| 1910117 (103)		| 1891584 (104)
| 10	| trend.mmd0			| 6636032	| 6566501	| 6616576 (98)		| 6545408 (99)

Attempted alternate values:

| Speed	| Module			| xmp (PAL table)	| xmp (NTSC table)	|
|-------|-------------------------------|-----------------------|-----------------------|
| 1	| privinv.mmd1			| 			| 15022080 (180)
| 3	| frequency confusion.mmd1	| 8437349 (151)		|
| 4	| to the house.mmd1		| 13916773 (139)	|
| 6	| memories of anna.mmd1		| 			| 18051584 (124)

Revised table:

| Speed | BPM (PAL)	| BPM (NTSC) |
|-------|---------------|------------|
| 1	| 178		| 180*
| 2	| 163		| 165
| 3	| 150		| 152
| 4	| 140		| 141
| 5	| 130		| 132
| 6	| 122		| 124*
| 7	| 115		| 116
| 8	| 109		| 110
| 9	| 103		| 104
| 10	| 98		| 99

Finally, doing a little bit of digging after determining those BPM values, I came up with:

BPMpal	≈ `(7093790Hz / 362) / (100 + speed * 10)`
BPMntsc	≈ `(7159090Hz / 362) / (100 + speed * 10)`

`(100 + speed * 10)` is derived from a table of buffer sizes in an otherwise incomprehensible M68k assembly player for 8-channel mode MEDs; `362` is a magic number I estimated and I don't know the significance of it (I'm not really familiar with the Amiga...). There's a separate table of HQ mode buffer sizes but since the user has to enable that manually it's probably not worth supporting.

I haven't done any testing of non-integer BPM values since neither xmp nor MikMod directly support them (more precise integer values for xmp could probably be determined with a different time factor though).

Tentative patch: https://github.com/libxmp/libxmp/compare/master...AliceLR:fix-med-8-channel-mode-tempo, but I think this issue should probably be looked at a little bit more before I PR it.

Tagging @sagamusix, who noticed this in a [report for a different 8-channel mode issue](https://bugs.openmpt.org/view.php?id=1386).

**Comment by sagamusix** [comment]
FWIW, OpenMPT is now back to using the table as MED Soundstudio seems to use on import, which is as follows: 179, 164, 152, 141, 131, 123, 116, 110, 104, 99
