### ISSUE TITLE
Portamento, volume slide effects lag behind 1 frame.

### ISSUE THREAD

**Issue by AliceLR** [libxmp/libxmp#242]
I've noticed in some test modules that portamento and volume slide effects lag behind a frame (including "fine" effects that should be immediately executed during the first frame). This happens because the virtual channel volume/frequency data is configured prior to these effects being processed for the frame. https://github.com/libxmp/libxmp/blob/master/src/player.c#L1297

[vslide_lag.it.zip](https://github.com/libxmp/libxmp/files/5609611/vslide_lag.it.zip): in Impulse Tracker and OpenMPT, this module is silent. In xmp, the note plays at volume 15 for a single tick because the volume slide is applied after data is provided to the virtual channels. This also happens in MikMod (edit: unrelated. MikMod doesn't execute new-effects IT volslides on the first tick for some reason).

[portamento_offset_after_keyoff.it.zip](https://github.com/libxmp/libxmp/files/5609616/portamento_offset_after_keyoff.it.zip): in Impulse Tracker, OpenMPT, and MikMod, the notes in this module that use portamento without offset play at roughly the same time as the notes that do have an offset. In xmp they lag behind, creating a noticeable "swing" that shouldn't be there.

Panbrello is probably also affected since `update_pan` is called after `process_pan`.

I'm sure there's a reason it was implemented like this but I've confirmed that at least two players do not behave this way (Impulse Tracker, BWSB), and I'm sure there are more. Calling the update functions before the process functions improves these two test cases but predictably makes 76 tests fail. This might also subtly break other things that worked correctly before.

This seems like a serious issue, but how should we go about fixing it?

edit: I'll update this as I test different players.

| Format / tested player | Update first? | Example file |
|-|-|-|
| IT / Impulse Tracker 2.14 | Yes. | see above. |
| MOD / ProTracker 2.3, 3.15 | Yes. | [vslide_lag.mod.zip](https://github.com/libxmp/libxmp/files/5610258/vslide_lag.mod.zip) |
| S3M / Scream Tracker 3.21 | Yes. | [vslide_lag.s3m.zip](https://github.com/libxmp/libxmp/files/5609957/vslide_lag.s3m.zip) |
| XM / Fasttracker 2.09a | Yes. | [vslide_lag.xm.zip](https://github.com/libxmp/libxmp/files/5609973/vslide_lag.xm.zip) |
| DBM / DigiBooster Pro 2.13 | Yes. | Import the example MOD. |
| FAR / Farandole Composer 1.00 | Yes. | [VSLIDELG.FAR.zip](https://github.com/libxmp/libxmp/files/5610386/VSLIDELG.FAR.zip) (note: xmp handling of FAR effects also causes volslides to be much weaker than they should be, but it's enough to verify that xmp is applying it on the wrong tick.) |
| GDM / BWSB 1.21 GDMPLAY.EXE | Yes. | Use BWSB's SB16 driver since some effects are broken in the GUS driver: [VSLIDE~1.GDM.zip](https://github.com/libxmp/libxmp/files/5609959/VSLIDE.1.GDM.zip) |
| MED / OctaMED 2.00, 4.03, 5.00, SS 1.03 | Yes. | [vslide_lag.med.zip](https://github.com/libxmp/libxmp/files/5610316/vslide_lag.med.zip) (note: MED slides) |
| OKT / Oktalyzer 1.57 | Yes. | [vslide_lag.okt.zip](https://github.com/libxmp/libxmp/files/5610302/vslide_lag.okt.zip) |
| ULT / UltraTracker 1.6 | ??? | [VSLIDEX1.ULT.zip](https://github.com/libxmp/libxmp/files/5611302/VSLIDEX1.ULT.zip) and [VSLIDEX2.ULT.zip](https://github.com/libxmp/libxmp/files/5611303/VSLIDEX2.ULT.zip). Hard to tell because the volume is on a scale from 0-255. Volslide down and fine volslide down both click identically in UltraTracker. With one fine slide down, xmp clicks comparably to UltraTracker. xmp can't handle two slides down on the same frame. |

**Comment by AliceLR** [comment]
I think considering the four "core" formats and several other prominent formats (MED, DBM, GDM...) all apply effects when reading the event (not after sending data to the sound card), it is clear the order of update/process needs to be flipped. Also worth noting DBM, GDM, ULT all allow multiple of the same effect in a single channel/row and the current approach of storing effects in a single place in the channel_data struct to apply them later prevents those from working.

**Comment by cmatsuoka** [comment]
I think the expected values in tests are wrong. Look at the expected values for volume during a slide in the `effect_a_volslide` test: it wants the update to happen after the volume is processed, so not updating in the first frame would result in 64, 64, 62, 60. If updating before, the result would be a nicer 64, 62, 60, 58. Which means that we'll have to make sure this is the correct behavior, and then update the test results where needed.

Looking at the [NoiseReplay source code](https://github.com/cmatsuoka/hazemod/blob/master/doc/player/NoiseReplayV1.1#L348), we can see that it updates the volume value before sending it to Paula (in `mt_vol2`).

Why was it done this way? I really don't remember, and there's also the possibility that there's code compensating this error somewhere else in the codebase for some situations, and we would also need to clean that up.

**Comment by cmatsuoka** [comment]
But we'll still have a broken step between the last tick of a row and the first tick in the next row (which will have the same volume), is that correct?

**Comment by AliceLR** [comment]
I think that is correct—`Axy` volslide doesn't update on tick 0 unless `QUIRK_VSALL` is set, so it would have the same volume from the last tick of the previous row.

**Comment by cmatsuoka** [comment]
I'll start to evaluate the tests that fail to confirm that they're testing against bad reference values and fix them.

**Comment by cmatsuoka** [comment]
Manual verification of the failed test cases revealed two additional problems, reported in issues #260 and #261.

**Comment by AliceLR** [comment]
> It also would be interesting to remake the "Note after cut" test to include only the case being tested.

To clarify, are rows 42-44 the only part of this test module relevant to the feature being tested?
