### ISSUE TITLE
IT volume envelope shape error

### ISSUE THREAD

**Issue by cmatsuoka** [libxmp/libxmp#261]
Re-evaluation of the OpenMPT IT volume envelope carry test case shows a mismatch in the envelope shape with seemingly longer tails in release. (see attached image at approx. 1.55s)

![image](https://user-images.githubusercontent.com/317355/101354749-66fab400-3874-11eb-9cb5-32ca7b7c5b4f.png)

**Comment by AliceLR** [comment]
I also noticed this issue while reviewing #262. It looks like the volume envelope being used has no loop and never drops in volume so this might be a fade issue.

![image](https://user-images.githubusercontent.com/1750531/101442391-7e6b8880-38d8-11eb-93f5-389e89a066b1.png)

**Comment by AliceLR** [comment]
Reversing these two blocks in player.c so the envelope updates before checking for fadeout seems to help (don't know whether or not it's the correct fix but it seems at least plausible):
```C
        if (!TEST_PER(VENV_PAUSE)) {
                xc->v_idx = update_envelope(&instrument->aei, xc->v_idx,
                        DOENV_RELEASE, TEST(KEY_OFF), IS_PLAYER_MODE_IT());
        }
```
```C
        switch (check_envelope_fade(&instrument->aei, xc->v_idx)) {
        case -1:
                SET_NOTE(NOTE_END);
                /* Don't reset channel, we may have a tone portamento later
                 * virt_resetchannel(ctx, chn);
                 */
                break;
        case 0:
                break;
        default:
                if (HAS_QUIRK(QUIRK_ENVFADE)) {
                        SET_NOTE(NOTE_FADEOUT);
                }
        }
```

**Comment by AliceLR** [comment]
Another thing that helps is moving the fade handling after the envelope handling:
![image](https://user-images.githubusercontent.com/1750531/101451357-3ef96800-38e9-11eb-9bc7-1c85a55d3bbc.png)

**Comment by AliceLR** [comment]
After checking OpenMPT and libmodplug, both apply fadeout after the volume envelope position has been incremented, so *both* changes I mentioned seem to be on the right track. The first change should make `check_envelope_fade` (which initiates the fade at the end of the volume envelope) happen after the envelope increment. The second change makes `NOTE_FADEOUT` apply immediately after `check_envelope_fade` instructs `process_volume` to start the fade. @sagamusix do these observations generally line up with reality?

I can write a patch for this, but I need to verify it against other players. Potential affected formats:
```
src/loaders/it_load.c:428:      xxi->rls = i1h.fadeout << 7;
src/loaders/it_load.c:570:      xxi->rls = i2h.fadeout << 6;
src/loaders/mdl_load.c:703:             xxi->rls = x;
src/loaders/rtm_load.c:430:             xxi->rls = ri.volfade;
src/loaders/xm_load.c:484:                      xxi->rls = xi.v_fade << 1;
src/loaders/hsc_load.c:132:     mod->xxi[i].rls = LSN(sid[7]) * 32;     /* carrier release */
```
```
src/loaders/flt_load.c:401:             xxi->rls = 0xfff;
src/loaders/mmd_common.c:576:   xxi->rls = 0xfff - (exp_smp->decay << 4);
src/loaders/mmd_common.c:688:   xxi->rls = 0xfff - (exp_smp->decay << 4);
src/loaders/fcm_load.c:89:      mod->xxi[i].rls = 0xfff;
src/loaders/ims_load.c:223:     //mod->xxi[i].rls = 0xfff;
src/loaders/mfp_load.c:140:             mod->xxi[i].rls = 0xfff;
src/loaders/polly_load.c:194:           mod->xxi[i].rls = 0xfff;
src/loaders/pt3_load.c:257:             mod->xxi[i].rls = 0xfff;
src/loaders/pw_load.c:145:              mod->xxi[i].rls = 0xfff;
src/loaders/stim_load.c:194:            mod->xxi[i].rls = 0xfff;
```

From what I remember OctaMED hold/decay has problems already and can be ignored. Not sure what's going on with the ones that use fixed values, but I'm guessing they don't matter particularly much either.

**Comment by sagamusix** [comment]
Makes sense, based on a quick read.

**Comment by AliceLR** [comment]
Test module with 4 ticks of nothing, 4 ticks of envelope fade in, and 4 ticks of fade out. Even with both fixes applied, libxmp is still losing a tick from somewhere, but it's close enough that it might not matter that much.

![image](https://user-images.githubusercontent.com/1750531/123508416-88fb2e80-d62c-11eb-9fb4-f8c886a8cbc2.png)

It might be an off-by-one in this check in `check_envelope_fade`, since IT never plays a tick at full volume between the envelope and fade out, suggesting the first fade tick is applied the exact same tick the envelope caps (seems like an IT bug to me):
```C
	index = (env->npt - 1) * 2;		/* last node */
	if (x > data[index]) {
		if (data[index + 1] == 0)
			return -1;
		else
			return 1;
	}
```
