### ISSUE TITLE
DLL API of libxmp to use in NehQuake engine

### ISSUE THREAD

**Issue by Alex3474247** [libxmp/libxmp#313]
Hello! I want to ask you which DLL APIs and external symbols should I use in code in the Nehahra quake engine source (it is C project in visual C++ 6.0) to play the XM files in game? There are 2 console commands in Nehahra to play .xm: playmod and stopmod.

**Comment by sezero** [comment]
It's been ages since I last looked at nehahra source. However, the quakespasm
code might be useful to you:
https://sourceforge.net/p/quakespasm/quakespasm/ci/master/tree/
See snd_xmp.c in there for the libxmp specific parts.
