### ISSUE TITLE
Memory leaks, memory errors revealed by libfuzzer / valgrind, step 5

### ISSUE THREAD

**Issue by debrouxl** [libxmp/libxmp#323]
New issue for the remainder of new batch 4 (#319 , starting from https://github.com/libxmp/libxmp/issues/319#issuecomment-792051867 if I'm not mistaken), as suggested in #319 ,  and a new issue, which has just stopped a fantastic ride - 350+M tests over days ! - of the libfuzzer-based front-end.
It still reproduces in current HEAD 3bc0317c9ab59361bcd16c729dcd34c90f2fb32e , that's where the line numbers ought to be from.
```
Loading ./crash-f162b7a3cac06ff685176ce73e052a599c8a080a (1 of 1)
=================================================================
==3702430==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000038 at pc 0x7ffae14bbcea bp 0x7ffe25947130 sp 0x7ffe25947128
READ of size 4 at 0x602000000038 thread T0
    #0 0x7ffae14bbce9 in fnk_load .../xmp/libxmp/src/loaders/fnk_load.c:233:2
    #1 0x7ffae1434071 in load_module .../xmp/libxmp/src/load.c:461:18
    #2 0x7ffae14331a9 in xmp_load_module .../xmp/libxmp/src/load.c:613:8
    #3 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #4 0x7ffae0ecfd09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #5 0x420679 in _start (.../bin/xmp+0x420679)

0x602000000038 is located 0 bytes to the right of 8-byte region [0x602000000030,0x602000000038)
allocated by thread T0 here:
    #0 0x49a862 in calloc (.../bin/xmp+0x49a862)
    #1 0x7ffae1442c50 in libxmp_alloc_pattern .../xmp/libxmp/src/loaders/common.c:164:18
    #2 0x7ffae1442c50 in libxmp_alloc_pattern_tracks .../xmp/libxmp/src/loaders/common.c:212:6
    #3 0x7ffae14ba20f in fnk_load .../xmp/libxmp/src/loaders/fnk_load.c:230:6
    #4 0x7ffae1434071 in load_module .../xmp/libxmp/src/load.c:461:18
    #5 0x7ffae14331a9 in xmp_load_module .../xmp/libxmp/src/load.c:613:8
    #6 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #7 0x7ffae0ecfd09 in __libc_start_main csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow .../xmp/libxmp/src/loaders/fnk_load.c:233:2 in fnk_load
```
[fnk_oob_read_2.tar.gz](https://github.com/libxmp/libxmp/files/6119150/fnk_oob_read_2.tar.gz)

Some stats: barring a stupid event (computer crash, etc.):
* the three oldest AFL++ instances have recently surpassed 8G combined execs, and will soon reach 100 days of "run time" (probably wall clock, so not taking the occasional 1-2h suspend/resume cycles into account) each;
* several days later, the combined 4 AFL++ instances should reach a year of run time;
* several days after that, the combined 4 AFL++ instances should reach 10G execs, which would be a milestone as good as any to stop them, I suppose.

Now that ASAN-instrumented builds of the code base can survive dozens of millions of tests, and given that MSAN-instrumented builds should follow suit, both mainly thanks to AliceLR's great work, a libfuzzer-based memory-loading-based front-end / an AFL++ persistent mode-based memory-loading-based front-end should be favored over a simplified, forking AFL++-based file-loading-based front-end. AFAICT from looking at load.c + hio.c, apart from stdio.h vs. memio.c/h functions, the two approaches should provide pretty much the same coverage.

**Comment by AliceLR** [comment]
I can start looking at batches 2-4 from #319 and this new crash soon, thanks!

**Comment by AliceLR** [comment]
> ...a libfuzzer-based memory-loading-based front-end / an AFL++ persistent mode-based memory-loading-based front-end should be favored over a simplified, forking AFL++-based file-loading-based front-end. AFAICT from looking at load.c + hio.c, apart from stdio.h vs. memio.c/h functions, the two approaches should provide pretty much the same coverage.

Even better than that, I think using the memio-based HIO_HANDLEs has helped uncover bugs that weren't reproduceable with stdio.h (I remember specifically needing to hack together an `xmp_load_module_from_memory`-based loader for some). Related, but do you think your libfuzzer frontend as mentioned in #302 is ready to pull request?

**Comment by debrouxl** [comment]
Nope, on my side, the libfuzzer front-end I've been using for the past few weeks isn't ready to pull request at the time of this writing.
Mostly, I didn't try hard enough to integrate the libfuzzer front-end into the libxmp build system. Makefile.in modifications for building front-end binary with `-fsanitize=fuzzer` are one thing, but I think that ultimately, what is needed are complementary but interacting configure.ac options to 1) enable building libxmp with a user-specified sanitizer and 2) enable building the libfuzzer front-end, which has an impact on the CFLAGS used for building libxmp, as I mentioned in passing in #302. WDYT ?

Also, in #302, I mentioned cleaning up leftover temp files, which are a huge issue with the still ongoing AFL++ runs with auto-tuned low timeouts (and lack of fixes for files which cause lengthy / infinite processing) and non-negligible crash rate. However:
* the latter is now fixed (asan-pointed errors) or soon will be (msan-pointed errors);
* with your fixes and a 1s timeout passed to libfuzzer or (certainly) AFL++, timeouts have become very infrequent when using an output directory located into the ramdisk.

Therefore, cleaning up leftover temp files could well be a non-issue for the libfuzzer front-end.

In #302, I mentioned a crash with 0-sized input.

**Comment by AliceLR** [comment]
I've fixed the issues with the most samples in batches 2-4 that I could reproduce with MSan:
```
DIGI Booster truncated mod title and instrument names:
	246d3...
	2bb45...
	2ddce...
	63767...
	66075...
	74206...
	7a4b8...
	8968a...
	c4b12...
	ccffe...
	e1b1b...
	e769e...
	ecb54...

Ultra Tracker truncated patterns:
	010aa...
	034bb...
	0c776...
	1065a...
	4b9fb...
	8b16f...
	c10e6...
	e0ea8...
	ef417...

Ultra Tracker truncated instrument names:
	803c6...
```
There are three more files that MSan detected issues for in various loaders (one in the ST .MOD loader!). The rest are the kind that start with `1A 02` and probably need to be tested with valgrind and/or the aforementioned memory loader to get useful info.

I also added a format test for DIGI Booster since there didn't seem to already be one, so hopefully the fuzzers will be able to find more bugs with an actual sample. Progress here: https://github.com/libxmp/libxmp/compare/master...AliceLR:fix-uninitialized-reads-3

> Mostly, I didn't try hard enough to integrate the libfuzzer front-end into the libxmp build system. Makefile.in modifications for building front-end binary with `-fsanitize=fuzzer` are one thing, but I think that ultimately, what is needed are complementary but interacting configure.ac options to 1) enable building libxmp with a user-specified sanitizer and 2) enable building the libfuzzer front-end, which has an impact on the CFLAGS used for building libxmp, as I mentioned in passing in #302. WDYT ?

I think in general having some sanitizer flags with preset configurations (e.g. `--enable-asan`, `--enable-msan`...) would be a good idea and help get rid of the hacky aliases I use to test libxmp with the sanitizers right now (these are more or less the minimum required configurations to get useful output in my experience).
```
export ASAN_FLAGS="-O1 -fsanitize=address -fno-omit-frame-pointer -g"
export UBSAN_FLAGS="-O1 -fsanitize=undefined -fno-omit-frame-pointer -g"
export MSAN_FLAGS="-O1 -fsanitize=memory -fsanitize-memory-track-origins=2 -fno-omit-frame-pointer -g"

alias envASan='export CC=clang; export CXX=clang++; export CFLAGS="$ASAN_FLAGS"; export LDFLAGS="$ASAN_FLAGS";'
alias envMSan='export CC=clang; export CXX=clang++; export CFLAGS="$MSAN_FLAGS"; export LDFLAGS="$MSAN_FLAGS";'
alias envClear='unset CC CXX CFLAGS LDFLAGS'
```
Likewise, having a flag specifically to enable the libfuzzer frontend plus `-fsanitize=fuzzer` seems to make sense. (Is there a situation where `-fsanitize=fuzzer` would be wanted without the frontend?)

> In #302, I mentioned a crash with 0-sized input.

I opened #325 for this earlier since it turns out that behavior is specified in the API(!).

**Comment by AliceLR** [comment]
The remaining ST MOD, Liquid Tracker, and Titanics issues are now fixed in that branch. After having been unable to reproduce any issues with the remaining files from those tarballs, I went back and checked the traces and it looks like they were the same as The Player issues I fixed in my last PR. @debrouxl can you confirm these are all fixed on your end in https://github.com/libxmp/libxmp/compare/master...AliceLR:fix-uninitialized-reads-3? If so, I'll go ahead and open a PR for this.

**Comment by debrouxl** [comment]
Sure, I'm going to check my whole corpus against HEAD + your 6 patches :)
I got sidetracked by work stuff and other things.

**Comment by sezero** [comment]
> ```
> Loading /dev/shm/queue/cfd3b4f519b940018e162c57cf39fd80211ec7f8 (1232 of 2335)
> ==1774704== Conditional jump or move depends on uninitialised value(s)
> ==1774704==    at 0x4897F79: arcfs_extract (arcfs.c:140)
> ==1774704==    by 0x4897F79: decrunch_arcfs (arcfs.c:212)
> ==1774704==    by 0x485C709: decrunch (load.c:221)
> ==1774704==    by 0x485D0BC: xmp_load_module (load.c:575)
> ==1774704==    by 0x10BA33: main (main.c:399)
> ==1774704==  Uninitialised value was created by a stack allocation
> ==1774704==    at 0x4897D70: decrunch_arcfs (arcfs.c:206)
> ```

I guess we need to check the read header len value for this one, e.g.:
```diff
diff --git a/src/depackers/arcfs.c b/src/depackers/arcfs.c
index 03af60f..414b5c5 100644
--- a/src/depackers/arcfs.c
+++ b/src/depackers/arcfs.c
@@ -44,6 +44,7 @@ static int read_file_header(FILE *in, struct archived_file_header_tag *hdrp)
                return -1;
        hlen = read32l(in, &error) / 36;
        if (error != 0) return -1;
+       if (hlen < 1) return -1;
        start = read32l(in, &error);
        if (error != 0) return -1;
        /*ver =*/ read32l(in, &error);
```

**Comment by debrouxl** [comment]
Another part of the corpus yields another usage of uninitialized values:
```
Loading d8c3d7f87faffa00b0f35b2700e150cb14d3266f (1469 of 1557)
==1779831== Conditional jump or move depends on uninitialised value(s)
==1779831==    at 0x4873996: liq_load (liq_load.c:571)
==1779831==    by 0x485CE5C: load_module (load.c:461)
==1779831==    by 0x485D18B: xmp_load_module (load.c:613)
==1779831==    by 0x10BA33: main (main.c:399)
==1779831==  Uninitialised value was created by a stack allocation
==1779831==    at 0x4873326: liq_load (liq_load.c:252)
==1779831== 
==1779831== Conditional jump or move depends on uninitialised value(s)
==1779831==    at 0x487367A: liq_load (liq_load.c:573)
==1779831==    by 0x485CE5C: load_module (load.c:461)
==1779831==    by 0x485D18B: xmp_load_module (load.c:613)
==1779831==    by 0x10BA33: main (main.c:399)
==1779831==  Uninitialised value was created by a stack allocation
==1779831==    at 0x4873326: liq_load (liq_load.c:252)
==1779831== 
.../xmp_prefix_nosan/bin/xmp: d8c3d7f87faffa00b0f35b2700e150cb14d3266f: Error loading module
```

**Comment by AliceLR** [comment]
> I guess we need to check the read header len value for this one, e.g.:

I verified that this fix works and committed it to my branch. That fixes a little over half of the samples in the new tarball. The rest appear to be ProWizard-related. As far as I can tell I do not have a copy of `d8c3d...`.

**Comment by AliceLR** [comment]
The uninitialized read caused by `id:010143...` is caused by broken pattern counting in the Promizer 1.0c loader when the order list length is zero (zero length order list should still derive the order count from the entire order list, resulting in 1 pattern minimum, according to how the `pw_load.c` and both `mod_load.c` loaders work). The affected code was copypasted between three other Promizer loaders (including the deadcode `pm20.c` and `pm40.c`) so I fixed it in all of them. I also hacked together a Promizer 1.8a test file from the aforementioned input.

**Comment by debrouxl** [comment]
Near the end of the output for the other part of the corpus, there's a single occurrence of a new issue in the digi loader:
```
Loading 51d64887926843527718d1fa3b75a6cc814c7f62 (1368 of 1538)
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x484D572: libxmp_period_to_note (period.c:220)
==1875098==    by 0x485FE50: libxmp_decode_protracker_event (common.c:398)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x4C79008: log@@GLIBC_2.29 (w_log_template.c:32)
==1875098==    by 0x484D590: libxmp_period_to_note (period.c:224)
==1875098==    by 0x485FE50: libxmp_decode_protracker_event (common.c:398)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x4CB02E8: __ieee754_log_fma (e_log.c:61)
==1875098==    by 0x484D590: libxmp_period_to_note (period.c:224)
==1875098==    by 0x485FE50: libxmp_decode_protracker_event (common.c:398)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x4CB02F7: __ieee754_log_fma (e_log.c:85)
==1875098==    by 0x484D590: libxmp_period_to_note (period.c:224)
==1875098==    by 0x485FE50: libxmp_decode_protracker_event (common.c:398)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Use of uninitialised value of size 8
==1875098==    at 0x4CB0367: __ieee754_log_fma (e_log.c:114)
==1875098==    by 0x484D590: libxmp_period_to_note (period.c:224)
==1875098==    by 0x485FE50: libxmp_decode_protracker_event (common.c:398)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x4C70F74: round (s_round.c:40)
==1875098==    by 0x484D5A5: libxmp_period_to_note (period.c:224)
==1875098==    by 0x485FE50: libxmp_decode_protracker_event (common.c:398)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x4C70F79: round (s_round.c:42)
==1875098==    by 0x484D5A5: libxmp_period_to_note (period.c:224)
==1875098==    by 0x485FE50: libxmp_decode_protracker_event (common.c:398)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x4C70F8B: round (s_round.c:51)
==1875098==    by 0x484D5A5: libxmp_period_to_note (period.c:224)
==1875098==    by 0x485FE50: libxmp_decode_protracker_event (common.c:398)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x485FE6E: libxmp_decode_protracker_event (common.c:401)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x485FD4A: libxmp_disable_continue_fx (common.c:411)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x485FD4E: libxmp_disable_continue_fx (common.c:412)
==1875098==    by 0x485FD4E: libxmp_disable_continue_fx (common.c:409)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x485FD50: libxmp_disable_continue_fx (common.c:412)
==1875098==    by 0x485FD50: libxmp_disable_continue_fx (common.c:409)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x485FD54: libxmp_disable_continue_fx (common.c:412)
==1875098==    by 0x485FD54: libxmp_disable_continue_fx (common.c:409)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x485FD62: libxmp_disable_continue_fx (common.c:412)
==1875098==    by 0x485FD62: libxmp_disable_continue_fx (common.c:409)
==1875098==    by 0x48720CF: digi_load (digi_load.c:209)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x48720E4: digi_load (digi_load.c:210)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x48720E8: digi_load (digi_load.c:210)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x487207B: digi_load (digi_load.c:206)
==1875098==    by 0x485CE5C: load_module (load.c:461)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x4854ECD: scan_module.part.0 (scan.c:295)
==1875098==    by 0x4855AC7: scan_module (scan.c:74)
==1875098==    by 0x4855AC7: libxmp_scan_sequences (scan.c:544)
==1875098==    by 0x485D028: load_module (load.c:527)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x4855185: scan_module.part.0 (scan.c:346)
==1875098==    by 0x4855AC7: scan_module (scan.c:74)
==1875098==    by 0x4855AC7: libxmp_scan_sequences (scan.c:544)
==1875098==    by 0x485D028: load_module (load.c:527)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x4855280: scan_module.part.0 (scan.c:407)
==1875098==    by 0x4855AC7: scan_module (scan.c:74)
==1875098==    by 0x4855AC7: libxmp_scan_sequences (scan.c:544)
==1875098==    by 0x485D028: load_module (load.c:527)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x48552AA: scan_module.part.0 (scan.c:416)
==1875098==    by 0x4855AC7: scan_module (scan.c:74)
==1875098==    by 0x4855AC7: libxmp_scan_sequences (scan.c:544)
==1875098==    by 0x485D028: load_module (load.c:527)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
==1875098== 
==1875098== Conditional jump or move depends on uninitialised value(s)
==1875098==    at 0x48552D3: scan_module.part.0 (scan.c:422)
==1875098==    by 0x4855AC7: scan_module (scan.c:74)
==1875098==    by 0x4855AC7: libxmp_scan_sequences (scan.c:544)
==1875098==    by 0x485D028: load_module (load.c:527)
==1875098==    by 0x485D18B: xmp_load_module (load.c:613)
==1875098==    by 0x10BA33: main (main.c:399)
==1875098==  Uninitialised value was created by a stack allocation
==1875098==    at 0x4871BEF: digi_load (digi_load.c:101)
```

[libxmp_remaining_uninitialized_323_20210322.tar.gz](https://github.com/libxmp/libxmp/files/6180151/libxmp_remaining_uninitialized_323_20210322.tar.gz) (contains `d8c3d...`)

**Comment by sezero** [comment]
> Another part of the corpus yields another usage of uninitialized values:
> ```
> Loading d8c3d7f87faffa00b0f35b2700e150cb14d3266f (1469 of 1557)
> ==1779831== Conditional jump or move depends on uninitialised value(s)
> ==1779831==    at 0x4873996: liq_load (liq_load.c:571)
> ==1779831==    by 0x485CE5C: load_module (load.c:461)
> ==1779831==    by 0x485D18B: xmp_load_module (load.c:613)
> ==1779831==    by 0x10BA33: main (main.c:399)
> ==1779831==  Uninitialised value was created by a stack allocation
> ==1779831==    at 0x4873326: liq_load (liq_load.c:252)
> ==1779831== 
> ==1779831== Conditional jump or move depends on uninitialised value(s)
> ==1779831==    at 0x487367A: liq_load (liq_load.c:573)
> ==1779831==    by 0x485CE5C: load_module (load.c:461)
> ==1779831==    by 0x485D18B: xmp_load_module (load.c:613)
> ==1779831==    by 0x10BA33: main (main.c:399)
> ==1779831==  Uninitialised value was created by a stack allocation
> ==1779831==    at 0x4873326: liq_load (liq_load.c:252)
> ==1779831== 
> .../xmp_prefix_nosan/bin/xmp: d8c3d7f87faffa00b0f35b2700e150cb14d3266f: Error loading module
> ```

Something like this is needed:
```diff
diff --git a/src/loaders/liq_load.c b/src/loaders/liq_load.c
index 1386292..15445b5 100644
--- a/src/loaders/liq_load.c
+++ b/src/loaders/liq_load.c
@@ -566,7 +566,9 @@ next_pattern:
 
        sub = &xxi->sub[0];
 
-       hio_read (b, 1, 4, f);
+       if (hio_read (b, 1, 4, f) < 4) {
+           return -1;
+       }
 
        if (b[0] == '?' && b[1] == '?' && b[2] == '?' && b[3] == '?')
            continue;
```

**Comment by AliceLR** [comment]
> Something like this is needed:

I've confirmed that this patch fixes the issue and have added it to my branch.

**Comment by AliceLR** [comment]
The Player 4.x uninitialized reads bug in the ProWizard pattern loader was the same thing as with the Promizer loaders, except with this time no convincing way to patch it out of the depacker—the depacker creates a unique pattern for every order of the module, so a zero length module just won't have any patterns. I just added an `hio_read` return value check in the common ProWizard pattern loading code to reject this (and any further issues like it that come up).

**Comment by AliceLR** [comment]
The DIGI Booster uninitialized read was caused by missing `hio_read` return value checks in two places during pattern loading. I added test files for both places this could happen. I think that's everything in both tarballs accounted for except for `2e222...`, which I wasn't able to replicate a bug for.

**Comment by AliceLR** [comment]
(I just checked the diff and there are >10 commits in this branch, so I'm going to go ahead and open the PR for it now.)

**Comment by debrouxl** [comment]
2e222d9d462b936d45c58e0c180e2af8be1aa07b is indeed a mistake on my side. It happened to be the file right before cfd3b4f519b940018e162c57cf39fd80211ec7f8 , and was included in the 5-line grep context for lines starting by "==" produced by valgrind. So yeah, good work, and definitely PR time :)
