### ISSUE TITLE
xmp_load_module_from_memory disables bounds checks when size <= 0.

### ISSUE THREAD

**Issue by AliceLR** [libxmp/libxmp#325]
> the size of the module, or 0 if the size is unknown or not specified. If size is set to 0 certain module formats won't be recognized, the MD5 digest will not be set, and module-specific quirks won't be applied.

https://github.com/libxmp/libxmp/blob/master/docs/libxmp.rst#int-xmp-load-module-from-memory-xmp-context-c-const-void-mem-long-size

```C
	/* Use size < 0 for unknown/undetermined size */
	if (size == 0)
		size--;
```
https://github.com/libxmp/libxmp/blob/master/src/load.c#L632

What exactly is the use case for this behavior? When will the user *not* know the size of the memory buffer that is provided? Should this really be encouraged? This seems comically unsafe and is the cause of a crash found in #302.

**Comment by sezero** [comment]
I truly don't like it, it really is seeking for trouble.

@cmatsuoka?

**Comment by AliceLR** [comment]
(My opinion for whatever it's worth: this should be removed ASAP, the field should be made an `unsigned long` for 4.5.0 and should be extended to `size_t` for 5.0.)

**Comment by sezero** [comment]
> (My opinion for whatever it's worth: this should be removed ASAP,

Seconded, although it is a behavior change, alhough+ I don't know whether anyone relies on that..

> the field should _maybe_ be made an `unsigned long` for 4.5.0, and should be extended to `size_t` for 5.0.)

Which field, the `long` size one? I think it should stay signed so we can easily check for bad args :)
For 5.0, `ptrdiff_t` or `ssize_t` maybe?

**Comment by AliceLR** [comment]
> Which field, the `long` size one? I think it should stay signed so we can easily check for bad args :)
> For 5.0, `ptrdiff_t` or `ssize_t` maybe?

Yes, I think you're correct, which is why I added "maybe": if anyone is actually using a negative value it'd be good to catch it, so leaving it for now and a `ptrdiff_t` for 5.0 would be better.

**Comment by cmatsuoka** [comment]
Remove it. I agree that if we load from a memory buffer we should know what data we're dealing with. It was probably added a long time ago without considering any robustness implication.

**Comment by sezero** [comment]
> Remove it. I agree that if we load from a memory buffer we should know what data we're dealing with. It was probably added a long time ago without considering any robustness implication.

I'll be working on a patch shortly.
