### ISSUE TITLE
AMF findings

### ISSUE THREAD

**Issue by sagamusix** [libxmp/libxmp#350]
I recently found that [DSMI](https://github.com/ochrons/dsmi/) was open-sourced by its author and dug through its code to solve some of the mysteries surrounding missing format revisions, and claims made in many older AMF loaders (such as that of libxmp).

Here are some things that should be addressed in libxmp:
- The panning command is 7-bit panning + surround, like in S3M. In fact, I asked Otto Chrons if DMP/DSMI is the source of this command, because it's the earliest source I have found, and he recalls that he added those commands to MOD/S3M at a time when the trackers themselves didn't.
- In AMF version 1 (currently not supported by libxmp, and I have no such files), the length of each track should be extended by 1 (i.e. 3 extra bytes compared to later revisions), unless the track length is 0.
- The track length is in fact not a 24-bit integer, but a 16-bit integer followed by a track type byte. Most of the time this type byte is 0, but in `AVOID.AMF` (can be found in the DSMI repository linked above) it isn't always 0, so the tracks start to appear to be huge halfway through.
- In file versions < 10, the loop start and end are 16-bit variables instead of 32-bit variables. There are v8 and v9 files in the DSMI repository for testing.
- File versions 1 and 8 are hardcoded to 4 channels (the byte containing the number of channels is not present in the header)
- Panning table for 16 channels is introduced in format version 9.
- There is some weird fingerprinting for files that supposedly only contain a 16-bit loop start and no loop end. I think this is a fairy tale coming from Miodrag Vallat's AMF.TXT. There are even two filenames cited in the source, but not even the original DSMI source code handles this special case (while otherwise keeping excellent backwards compatibility), so I would suspect that those files were simply broken. Without seeing those files myself, I refuse to believe that this information is correct. :)

Note: DSMI itself rejects file versions 0 and 2-7, so I suppose they don't exist.

**Comment by AliceLR** [comment]
Thanks for the detailed info; a patch was submitted to MikMod recently (https://github.com/sezero/mikmod/pull/36) that lines up with a lot of your observations, so since I need to verify a lot of this anyway I'll go ahead and patch these bugs soon.

**Comment by AliceLR** [comment]
Noticed something interesting while writing my own AMF utility: libxmp's track translation seems very suspicious.
```C
        /* Tracks */

        trkmap = calloc(sizeof(int), mod->trk);
        if (trkmap == NULL)
                return -1;
        newtrk = 0;

        for (i = 0; i < mod->trk; i++) {                /* read track table */
                uint16 t;
                t = hio_read16l(f);
                trkmap[i] = t;
                if (t > newtrk) newtrk = t;
        }

        for (i = 0; i < mod->pat; i++) {                /* read track table */
                for (j = 0; j < mod->chn; j++) {
                        int k = mod->xxp[i]->index[j] - 1;

                        /* Use empty track if an invalid track is requested
                         * (such as in Lasse Makkonen "faster and louder")
                         */
                        if (k < 0 || k >= mod->trk)
                                k = 0;
                        mod->xxp[i]->index[j] = trkmap[k];
                }
        }

        mod->trk = newtrk;              /* + empty track */
        free(trkmap);
```
What I've managed to gather from looking at real files and the (as you've mentioned, questionable at best) format document, the order list stores "logical" track numbers, which don't seem to have much of a consistent pattern between modules, but are always in the range [1,num_tracks]. The track table later in the module then acts as the mapping for logical tracks on the range [1,num_tracks] to stored tracks on the range [1,num_stored_tracks]. Though I haven't encountered it yet, in both cases, 0 is implied to signify an empty track.

libxmp loads the track table to index 0 of the table, then subtracts 1 from the logical tracks, maps out-of-bounds values to 0, and reads the value at this index from the track table as the new track value. This means 0 or >num_tracks tracks would get mapped to the *first* track (which was mapped to index 0 of the translation table), not the empty track (which is supposed to be mapped to index 0).

I don't know if this matters or not because I haven't encountered it and I haven't collected data from my AMF collections yet. Will report back on this. (The missing loop end probing that you mentioned also does seem suspicious, and doesn't match any real file I've encountered so far.)

**Comment by AliceLR** [comment]
Now that I can scan all of my AMF modules, I've confirmed that the track index 0 bug is an actual issue: here's a module that's immediately and noticeably affected by this (the first track is duplicated several times in the first order, causing clipping). [cosmos st.amf.zip](https://github.com/libxmp/libxmp/files/6575123/cosmos.st.amf.zip)

Haven't found anything that actually uses the surround effect yet, but there are a pair of modules that use 3(!) effects in a track at the same time (one of them is always a junk `0xFF` effect with a parameter of `0x40`. It might be related to the volume command it's paired with).
[logarithmic digressions-original.amf.zip](https://github.com/libxmp/libxmp/files/6575124/logarithmic.digressions-original.amf.zip)
[sub oceanic shuttle.amf.zip](https://github.com/libxmp/libxmp/files/6575125/sub.oceanic.shuttle.amf.zip)

**Comment by AliceLR** [comment]
Another thing wrong in both libxmp and MikMod, probably because of AMF.TXT: the note value of 0x7f is misused (and in libxmp, a volume value of 0xff seems to be ignored). This doesn't indicate that the previous event should be duplicated, but instead that the current playing note in that track should be retriggered. This is almost always due to an instrument being used without a note in the original MOD. Volume values of 0xff are also found in MOD conversions where no volume effect is used.

https://github.com/ochrons/dsmi/blob/master/src/MODLOAD.C#L189
https://github.com/ochrons/dsmi/blob/master/src/AMPLAYER.ASM#L994

**Comment by sagamusix** [comment]
I'll have to have a look at some of those myself as well, because what you mentioned above - instrument without note being used - didn't even sound correct when playing some S3Ms in DMP using that feature, or converting those S3Ms to AMF and then playing the corresponding AMF file. For example the hihats in ARYX.S3M get butchered because of that in DMP.

**Comment by AliceLR** [comment]
If it helps, this appears to be the original version of `eye.amf`, edgelord sample names and all (I don't know if an original version of the Aladdin module exists). https://modarchive.org/index.php?request=view_by_moduleid&query=126547

**Comment by AliceLR** [comment]
Here's a module I created with Protracker 2.3d that produces `xx 7F FF` events when run through M2AMF.EXE. Interestingly, it reveals a bug libxmp and MikMod both have with regard to the original MOD that the instrument change doesn't get applied even though the note resets. OpenMPT loads and plays the original correctly but not the AMF.

[inst_no_note.zip](https://github.com/libxmp/libxmp/files/6581268/inst_no_note.zip)

**Comment by AliceLR** [comment]
I've started working on a patch for this, starting with the note 0x7f and volume issues: https://github.com/libxmp/libxmp/compare/master...AliceLR:amf-fixes

**Comment by AliceLR** [comment]
I've implemented fixes for everything reported here, and will open a PR soon. In the meantime, I've been rooting around trying to find anything resembling those unusual 1.0 AMFs, and while I haven't found them, I found some AMF modules that aren't on ModLand or Mod Archive (though many of them are).

These are from the Kosmic Archives CD-ROM Volume 1, all from the 1993 folder. These are mostly 1.0 and 1.1 AMFs. [KLF CD1 AMFs.zip](https://github.com/libxmp/libxmp/files/6583870/KLF.CD1.AMFs.zip)
Full CD-ROM is archived here: https://archive.org/details/KOSMICD1.tar

These are from a website for a Netscape Navigator DSMI plugin. Wayback actually archived the modules! : ) They're probably just conversions of other peoples' music though, and are all 1.4 AMFs. [NPDSMI AMF.zip](https://github.com/libxmp/libxmp/files/6583890/NPDSMI.AMF.zip)
Source: https://web.archive.org/web/20040912204417/http://www.thetaband.com/npdsmi/nptest.html

**Comment by AliceLR** [comment]
After scraping [this thread on the Winamp forums](http://forums.shoutcast.com/showthread.php?t=96818), I now have some old copies of M2AMF.  M2AMF 1.02 produces AMF 0.8 modules and M2AMF 1.5 produces AMF 1.1 modules.  Still haven't found anything that creates the supposed buggy 1.0 modules.

**Comment by sagamusix** [comment]
1.02 is also the oldest version I have at hand. I would expect that the version 1 stuff probably never left a very small circle of people.

**Comment by AliceLR** [comment]
madbrain's website (archived) appears to have older versions of DMP, but they're all for OS/2 so I can't verify. http://web.archive.org/web/20010614174422/http://www.madbrain.com:80/software.html

**Comment by sagamusix** [comment]
Those version numbers cannot be in sync with the original DOS version; M2AMF 1.02 is from 1992 but DMP 1.0 for OS/2 is from 1995.

**Comment by AliceLR** [comment]
After some very lazy googling, some versions of Dual Module Player that aren't on ModLand:

[Dual Module Player 1.41](http://ftp.icm.edu.pl/packages/garbo/pc/sound/) has M2AMF 1.02 (AMF 0.8). [dmp141.zip](https://github.com/libxmp/libxmp/files/6587731/dmp141.zip)
[Dual Module Player 2.50](https://archives.scovetta.com/pub/dr_shareware_gold/music___/) has M2AMF 1.5 (AMF 1.1). [dmp250.zip](https://github.com/libxmp/libxmp/files/6587712/dmp250.zip)
[Dual Module Player 2.55](http://ftp.icm.edu.pl/packages/garbo/pc/sound/) has M2AMF 1.5 (AMF 1.1). [dmp255.zip](https://github.com/libxmp/libxmp/files/6587724/dmp255.zip)
[Dual Module Player 2.71](https://dose.0wnz.at/Shareware/Pegasus-4.0/SBLASTER/) has M2AMF 1.6 (AMF 1.1). [DMP271.ZIP](https://github.com/libxmp/libxmp/files/6587713/DMP271.ZIP)
[Dual Module Player 2.82](https://lostarchives.org/category/46/file/3583) has M2AMF 2.1 (AMF 1.3). [DMP282.ZIP](https://github.com/libxmp/libxmp/files/6587714/DMP282.ZIP)

Still nothing that helps, but at least this narrows the version ranges for both DMP and M2AMF.

**Comment by sagamusix** [comment]
btw,

>  I found some AMF modules that aren't on ModLand or Mod Archive (though many of them are).

Generally we try to keep the archives clean of conversions (people should listen to the original files where possible), but I realize that this can be problematic to tracker and player developers. I wonder if an additional archive for test tracks in various formats, like my playback compatibility tests, would be useful, and where it should be put so that it's useful for everyone.

**Comment by AliceLR** [comment]
FOUND IT!

The affected version is [Dual Module Player 2.32](https://dose.0wnz.at/Shareware/Pegasus-2.0/SOUND/), which is packed with M2AMF 2.32. This M2AMF emits AMF 1.0 files with the bizarre truncated instrument structs that the fingerprinting attempts to detect. Other versions may be effected, this is just the first one I found.

[DMP232.ZIP](https://github.com/libxmp/libxmp/files/6588134/DMP232.ZIP)

**Comment by sagamusix** [comment]
Awesome :tada:

**Comment by sagamusix** [comment]
Also thanks on behalf of @glennlunder who now archived all those DMP/DSMI versions on ModLand :)

**Comment by AliceLR** [comment]
That's good to hear! There were a handful more I found but didn't get around to checking and uploading that I can also post here when I get to it. Particularly, right now I copies of 2.65 and 2.70 are pending (found on an ISO), and I think I came across some others in the 2.80-2.90 range that weren't archived.
