### ISSUE TITLE
[Feature request] Add a xmp_load_module function for custom streams.

### ISSUE THREAD

**Issue by AliceLR** [libxmp/libxmp#351]
libopenmpt, MikMod, and libvorbis are all capable of opening files from a custom stream specified by a user-provided stream pointer and set of read/seek/tell callbacks. On the other hand, libxmp currently can *not* do this, and either a filename, `FILE *`, or buffer needs to be provided. This means that if the user is using their own IO abstraction either the underlying `FILE *`/buffer needs to be used (if available) or the stream content needs to be copied to a temporary buffer or file.

Considering 4.5.0 is still blocked on #344, it seems like adding an `HIO_HANDLE` type that operates on user-provided read/seek/tell callbacks (and corresponding `xmp_load_module` and `xmp_test_module` variants) could be added without further delaying a release. (This was briefly discussed in #134 due to the `fdopen` leak bug.)

Any thoughts?

**Comment by sezero** [comment]
Do you have a patch?

**Comment by AliceLR** [comment]
Not yet—I can take a look at it, but I want to work through some of that MikMod backlog first... :)
