### ISSUE TITLE
Remove S3M quirk87 "fix"

### ISSUE THREAD

**Issue by sagamusix** [libxmp/libxmp#360]
XMP's S3M loader has a fixup routine for a single broken S3M file. There are [good copies](https://modarchive.org/index.php?request=view_by_moduleid&query=72377) of that file so it's completely pointless to try to fix up the broken copy.

The comments in the source code say:

```
... doesn't start playing, just uses 100% cpu, number of patterns is unusually high

Claudio's fix: this module seems to be a bad conversion, bad rip or
simply corrupted since it has many instances of 0x87 instead of 0x00
in the module and instrument headers. I'm adding a simple workaround
to be able to load/play the module as is, see the fix87() macro below.
```

The only thing the S3M loader should do is not use 100% CPU on a broken file, so if that still happens after removing this fix it should obviously be fixed. But adding a workaround for a single broken file is otherwise just wrong.

**Comment by AliceLR** [comment]
Is the broken copy available somewhere? If it really caused hangs without this "fix" then I want to make sure whatever caused that is fixed now. (It doesn't look like something hard to replicate with a hex editor, though.)

**Comment by AliceLR** [comment]
I had to comment out a couple of safety checks I added to get my hacked copy of this module to load, but it does load now. Since the high bytes of the sample lengths were affected, what I think was happening was libxmp may have been trying to allocate/initialize very large sample buffers, which was something I saw cause hangs/high CPU usage with fuzzing inputs. This doesn't happen anymore (and the module normally would get rejected anyway due to the safety checks) so I think it's safe to just remove this hack.

**Comment by sagamusix** [comment]
It was replaced on scene.org yesterday. ;) Alas I didn't keep a copy of the original file...

**Comment by sagamusix** [comment]
@AliceLR The corrupted module version continues to live on in this ISO, in case you still want to verify: https://files.scene.org/view/mirrors/scenesp.org/compilations/modplanet/iso/modplanetbonus.zip

**Comment by AliceLR** [comment]
> It was replaced on scene.org yesterday. ;) Alas I didn't keep a copy of the original file...

Oh. :) I'll grab the ISO and check just to be sure. If it was hanging on sample allocation though, that was fixed, and if it was hanging on processing "patterns" of EOFs, that should also have been fixed.

**Comment by sagamusix** [comment]
Maybe it would also be helpful to add it as a regression test to the test suite?
