### ISSUE TITLE
Multiple tests failing on RISC OS

### ISSUE THREAD

**Issue by ccawley2011** [libxmp/libxmp#369]
> total:675  passed:644 (95.4%)  failed:31 ( 4.6%)

Almost all of the failing tests are related to the depackers. Some of them take unusually long and create temporary files > 100 MB.

A WIP branch with the initial changes required to build the tests is available here: https://github.com/ccawley2011/libxmp/tree/riscos-tests
The complete output from `libxmp-tests` is attached: [stdout.txt](https://github.com/libxmp/libxmp/files/6605086/stdout.txt)

**Comment by AliceLR** [comment]
From a quick look at the non-depacker tests that fail, they're all caused by depacking as well:

* `test_loader_j2b` (format is packed in MUSE)
* `test_fuzzer_gal*` (MUSE packed inputs)
* `test_fuzzer_mod_scan_row_limit` (XZ packed input)
* `test_fuzzer_prowizard_np2_patterns_bound` (XZ packed input)
* `test_fuzzer_prowizard_p61a_invalid_note` (one input is XZ packed)
* `test_api_smix_*` (uses a base module that is PowerPacker compressed)

**Comment by sezero** [comment]
> A WIP branch with the initial changes required to build the tests is available here: https://github.com/ccawley2011/libxmp/tree/riscos-tests

Looked at the two commits _very_briefly, looked OK.

**Comment by ccawley2011** [comment]
I tried looking at `test_depack_gzip`, and I'm at a loss as to what's wrong. The test passes when using the decompressed data, and using the test changes in https://github.com/ccawley2011/libxmp/commit/0d70c65783918617f532f655083cdcae9f5791b7, the output in `<Wimp$ScrapDir>.xmp_XXXXXX` and `<Wimp$ScrapDir>.ASDF` are both identical to the original decompressed data, which suggests that the depacker itself is working, but the output doesn't get recognized by any of the format loaders for some reason.

**Comment by ccawley2011** [comment]
> I don't know how that would be possible but, can this be in any way
> related to endianism? (What is the endianism of your test setup?)

RISC OS is little endian, so that's probably not it. It is quite picky about alignment, though, but I can't find any obvious place in the code that would attempt unaligned memory access.

Either way, I've sent an email to the GCCSDK mailing list asking for advice: http://www.riscos.info/pipermail/gcc/2021-June/007112.html

**Comment by AliceLR** [comment]
I can do a build in my ARMhf VM and see if anything comes up. I've definitely found unaligned access bugs in other places.

**Comment by ccawley2011** [comment]
> edit: potentially an issue with switching between write and read modes when seeking in the `w+b` tempfile?

That does seem to be the problem. I've pushed another test commit to the branch, and it works when closing the tempfile handle and reopening it. There's still one failing test remaining (`test_fuzzer_prowizard_p61a_invalid_note`), which may or may not be related, but the rest are now passing on RISC OS.

**Comment by AliceLR** [comment]
> That does seem to be the problem. I've pushed another test commit to the branch, and it works when closing the tempfile handle and reopening it.

I'm curious if the issue is isolated to `fseek`—does either a) replacing the `fseek` with `rewind` or b) preceding the `fseek` with `fflush` also fix the issue? Otherwise, if the `fclose`/`fopen` step needs to be kept, it might be better to restrict it RISC OS.

> There's still one failing test remaining (`test_fuzzer_prowizard_p61a_invalid_note`), which may or may not be related, but the rest are now passing on RISC OS.

There are actually 6 different tests in this file (and for some reason I didn't bother to give them different assert fail messages... oops). Do you know which one causes the failure?

**Comment by sezero** [comment]
Then it is an OS and/or libc issue?  An fllush() at line 261 of depacker.c indeed might fix things.

**Comment by AliceLR** [comment]
> Then it is an OS and/or libc issue? An fllush() at line 261 of depacker.c indeed might fix things.

I would suspect libc but I'm not sure. I set up a RISC OS development environment and it doesn't help that there appears to be two different libc implementations, the RISC OS system libc and a Unix compatibility libc. I haven't been able to actually build anything yet so I can't confirm anything or test.

**Comment by ccawley2011** [comment]
Calling `fflush()` after writing to the temporary file doesn't seem to have an effect. Disabling buffering entirely seems to fix all tests, however it does still produce overly large temporary files, as evidenced by the messages produced by RPCEmu in the native terminal about a lack of disk space.

> There are actually 6 different tests in this file (and for some reason I didn't bother to give them different assert fail messages... oops). Do you know which one causes the failure?

It appears to be test 5 on line 27 which fails. It seems that there's an issue with buffering on the input file, since it works with the compressed file when using the `setvbuf` hack, but not when using the decompressed file, or when closing and reopening the temporary file.

The most recent WIP changes can be found in this branch: https://github.com/ccawley2011/libxmp/tree/riscos-tests-2

**Comment by sezero** [comment]
Any progress on this?

**Comment by sezero** [comment]
Are any tests still failing in git master?

(BTW, if you have os-specific code for filetype.c::libxmp_get_filetype(), send a patch.
Also, I don't know whether riscos filesystem is case-insensitive: if it is we can make it
skip dirent functionality in loaders/common.c::libxmp_check_filename_case() )

**Comment by ccawley2011** [comment]
Here's an updated log file: [stdout.txt](https://github.com/libxmp/libxmp/files/6910138/stdout.txt)

> total:725  passed:696 (96.0%)  failed:29 ( 4.0%)

All but one of the tests are fixed with the previous hack of closing and reopening the temporary file in the depacking code. The one remaining test that fails is this ProWizard test:

> test 659: test_fuzzer_prowizard_p61a_invalid_note: at test_fuzzer_prowizard_p61a_invalid_note.c:27: module load: **fail**

**Comment by AliceLR** [comment]
If I got everything right, only 11 tests should be failing now thanks to #509, correct? (From stdout.txt above so the numbers are likely out-of-date.)

```
test 39: test_depack_rar: at test_depack_rar.c:20: can't load module: **fail**
test 43: test_depack_bzip2: at test_depack_bzip2.c:13: can't load module: **fail**
test 45: test_depack_lha_l0_lzhuff1: at test_depack_lha_l0_lzhuff1.c:13: can't load module: **fail**
test 47: test_depack_lha_l1_lzhuff5: at test_depack_lha_l1_lzhuff5.c:13: can't load module: **fail**
test 48: test_depack_lha_l1_lzhuff6: at test_depack_lha_l1_lzhuff6.c:13: can't load module: **fail**
test 49: test_depack_lha_l1_lzhuff7: at test_depack_lha_l1_lzhuff7.c:13: can't load module: **fail**
test 51: test_depack_lha_l0_filtered: at test_depack_lha_l0_filtered.c:13: can't load module: **fail**
test 52: test_depack_lha_l1_filtered: at test_depack_lha_l1_filtered.c:13: can't load module: **fail**
test 53: test_depack_lha_l2_filtered: at test_depack_lha_l2_filtered.c:13: can't load module: **fail**
test 652: test_fuzzer_prowizard_np2_patterns_bound: at test_fuzzer_prowizard_np2_patterns_bound.c:14: module load: **fail**
test 659: test_fuzzer_prowizard_p61a_invalid_note: at test_fuzzer_prowizard_p61a_invalid_note.c:27: module load: **fail**
```

**Comment by ccawley2011** [comment]
Updated log file: [stdout.txt](https://github.com/libxmp/libxmp/files/7824088/stdout.txt)

> total:771  passed:763 (99.0%)  failed:8 ( 1.0%)

Results are as expected, except for `test_depack_rar` which now passes.

**Comment by ccawley2011** [comment]
I've retested this now that PR #616 has been merged, and all tests pass now on RISC OS.
