### ISSUE TITLE
Weird behavior of the xmp_loader_med2 unit test

### ISSUE THREAD

**Issue by Wohlstand** [libxmp/libxmp#414]
While I working on the CMake build, I found that one of the unit tests has a weird behavior:

When I try to run the existing unit test and the Automake-built library, it reports the next:
```
med2_load [src/loaders/med2_load.c:221] [ 0] med2test_PanFlute                26ac 0000 0000   V40
```

But, when I try to run the player (`examples/player-sdl.c`),
```bash
LD_LIBRARY_PATH=../lib ./player-sdl '/home/vitaly/_git_repos/libxmp/test-dev/data/m/med2test.med'
```

it gives me the next result:
```
med2_load [src/loaders/med2_load.c:221] [ 0] med2test_PanFlute                0000 0000 0000   V40
```

And, the absolutely same case happens at unit tests when I build them by my CMake build, and this file gets failed because of zero sub-instruments.

Can you explain what happens with that file? Where is the error?

At the file, I do see the big block of zeroes. I didn't familiar with MED2 files, and therefore I can't tell, is this file valid or it's a bad file?
![изображение](https://user-images.githubusercontent.com/6751442/125201934-ec669c80-e279-11eb-8bb5-c649d1566641.png)

**Comment by Wohlstand** [comment]
Small addition: I had to debugged this case:
- the test check expects the 1 sub-instrument
- actually the med2 reader gave the 0 sub-instruments

**Comment by AliceLR** [comment]
This test reports zero subinstruments when it can't find and load the external sample file (MED2 is a song-only format). libxmp finds the subinstrument by searching `module_data::instrument_path`, which for this test is set to `data/m`. Are the tests being run from `test-dev/` (where this would work) or from the repository root (where it would not)?

I noticed this failed on another setup I ran the tests on, but I don't remember what it was. The MED2 loader could probably be modified to attempt to load samples from the module path if the preset instrument path doesn't work.

**Comment by Wohlstand** [comment]
> Are the tests being run from test-dev/ (where this would work) or from the repository root (where it would not)?

Hm...

The unit test binary was built at the `build/test-dev/` directory, but ran at the `test-dev` as a working directory :thinking: 
Lemme try to manually put the CMake-built executable into the `test-dev` and try to run it...

**Comment by Wohlstand** [comment]
Or another .... I'll make the symlink to the "data" directory at `build/test-dev` to verify the behavior, does the executable relying on the self path or not?

**Comment by AliceLR** [comment]
The test-dev executable does rely on the self path for Win32 and other non-fork builds (I forget what else uses that, but DJGPP and RISC OS come to mind).

**Comment by Wohlstand** [comment]
In the code, the RISC OS is only mentioned as non-fork builds. Also, I made the ability to enforce the non-fork build to run the test of one selected test case to debug it. And, in both variants (forked and non-forked), it still fail.

**Comment by AliceLR** [comment]
Does the patch in #416 fix this issue?

**Comment by Wohlstand** [comment]
I'll test this after sleep

**Comment by Wohlstand** [comment]
> Does the patch in #416 fix this issue?

Fixes, and in addition, the unit test fault is my direct fault: I missed up with the `HAVE_DIRENT` check, so, I added it, and now everything works at me, your patch fixes the player, now it works as intended :fox_face:

**Comment by sezero** [comment]
Since you added the missing dirent check, is #416 still needed though?

**Comment by Wohlstand** [comment]
Yes, needed, #416 fixes another problem that is more general, and I had to reproduce it at the example player with the Autotools-built library
