### ISSUE TITLE
stray fprintf() in mix_paula.c

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#458]
This: https://github.com/libxmp/libxmp/blob/master/src/mix_paula.c#L50
Should we change it to `D_(D_WARN "active blep list truncated!");` ?

**Comment by AliceLR** [comment]
Yes, that seems like it'd be a good idea. I did a quick search through the source tree for other instances of printf/fprintf and it looks like that's the only one still active in non-deadcode.

**Comment by sezero** [comment]
Pushed https://github.com/libxmp/libxmp/commit/2b07b65895bc3c4b580588855f685afad289759b
