### ISSUE TITLE
Emscripten, LIBXMP_EXPORT and symbol visibility attributes

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#467]
Both autotools and the yet-to-be-merged cmake build system checks for
symbol visibility attributes and use them if they are found and not blacklisted.
and:

- Emscripten is _not_ blacklisted, so I guess it is being used. (I don't know
  Emscripten, and I don't have any Emscripten toolchains, so can't check
  the generated makefiles, etc.)

- But: The XMP_SYM_VISIBILITY has precedence over EMSCRIPTEN_KEEPALIVE in xmp.h

So: What are we really doing here?? @AliceLR, @Wohlstand?

**Comment by Wohlstand** [comment]
The `EMSCRIPTEN_KEEPALIVE` is not the visibility at all, it's the marker that tells the optimizer to never treat the specific object as a dead code to strip it down.

**Comment by Wohlstand** [comment]
by the way, you can easily install the Emscripten toolchain into any directory of your computer easily:
https://emscripten.org/docs/getting_started/downloads.html
Nothing super-special at the system is needed. By the way, CI does install the Emscripten toolchain for every build.

**Comment by sezero** [comment]
> by the way, you can easily install the Emscripten toolchain into any directory

Maybe I can, but I have no intention of doing so.

**Comment by sezero** [comment]
I guess the key is the `XMP_SYM_VISIBILITY` macro? It is defined
(at least supposedly) only by libxmp during libxmp build. So the
emscripten-specific LIBXMP_EXPORT defines actually only serve the
user's of the library - is that correct? If it is, I guess we can
close this.

**Comment by Wohlstand** [comment]
> emscripten-specific LIBXMP_EXPORT defines actually only serve the user's of the library

Some sort of yes, It tells to not remove this call during the optimization of the release build.

**Comment by sezero** [comment]
> > emscripten-specific LIBXMP_EXPORT defines actually only serve the user's of the library
> 
> Some sort of yes, It tells to not remove this call during the optimization of the release build.

But then, only the variables (see common.h) and functions are getting marked with
EMSCRIPTEN_KEEPALIVE during libxmp build itself, not any of the libxmp functions.

**Comment by sezero** [comment]
> But then, only the variables (see common.h) are getting marked with
> EMSCRIPTEN_KEEPALIVE during libxmp build itself, not any of the libxmp functions.

Then again, maybe the vars are the only ones actually needing that??

**Comment by Wohlstand** [comment]
I guess @AliceLR knows a better answer to this question. Variables were marked differently because the standard way causes the build failure because of incorrect use of the `EMSCRIPTEN_KEEPALIVE` at public variables.

**Comment by AliceLR** [comment]
I can confirm this *might* be an issue: both from the CI checks and running `emconfigure ./configure` locally in my build VM, I get this output and `-DXMP_SYM_VISIBILITY` is added to the Makefile `CFLAGS`:
```
checking whether compiler understands -fvisibility=hidden... yes
checking whether compiler understands attribute externally_visible... no
checking whether compiler understands attribute __symver__... no
```
Additionally, adding `|emscripten*` to the switch on line 137 of configure.ac doesn't help. If I add a line to print `$host_os` before this switch, the output is:
```
configure: host os: linux-gnu
checking whether compiler understands attribute externally_visible... no
```
(I'm running an old Emscripten toolchain so who knows if this is still how it behaves.)

**Comment by sezero** [comment]
I don't know what `emconfigure` does, but SDL's buildbot configurationruns, unlike us:
`emconfigure ../configure --host=wasm32-unknown-emscripten [xxx]`

Maybe we should add the `--host=wasm32-unknown-emscripten` switch to our
github CI configuration, and also document it?

**Comment by AliceLR** [comment]
> Maybe we should add the `--host=wasm32-unknown-emscripten` switch to our
> github CI configuration, and also document it?

I think that would be OK. @Wohlstand?

**Comment by Wohlstand** [comment]
> I think that would be OK. @Wohlstand?

I guess yes, let's try

**Comment by sezero** [comment]
`--host=wasm32-unknown-emscripten` is now added to the CI emscripten autotools builds.
The only missing thing would be documenting that required switch in the `INSTALL` file, I guess.

Then we can close this?

**Comment by sezero** [comment]
Is the following `INSTALL` update OK?

```diff
diff --git a/INSTALL b/INSTALL
index 7dc0ad4..66e667a 100644
--- a/INSTALL
+++ b/INSTALL
@@ -22,15 +22,25 @@ run:
 
 Use ./configure --help to see more options.
 
+For emscripten, remember to pass the correct host os to configure, e.g.:
+
+  $ emconfigure ./configure --host=wasm32-unknown-emscripten
+
+
+You can also use the CMake build system to build libxmp, which requires
+cmake versions 3.2 or newer ( https://cmake.org )
+
 
 To build for Windows using Visual Studio, use Makefile.vc:
 
   nmake -f Makefile.vc   (read/edit Makefile.vc as necessary.)
 
+
 To build for Windows using OpenWatcom, use Makefile.w32:
 
   wmake -f Makefile.w32  (read/edit Makefile.w32 as necessary.)
 
+
 To build for OS/2 using OpenWatcom, use Makefile.os2:
 
   wmake -f Makefile.os2  (read/edit Makefile.os2 as necessary.)
```

**Comment by sezero** [comment]
> Is the following `INSTALL` update OK?

PING?

> ```diff
> diff --git a/INSTALL b/INSTALL
> index 7dc0ad4..66e667a 100644
> --- a/INSTALL
> +++ b/INSTALL
> @@ -22,15 +22,25 @@ run:
>  
>  Use ./configure --help to see more options.
>  
> +For emscripten, remember to pass the correct host os to configure, e.g.:
> +
> +  $ emconfigure ./configure --host=wasm32-unknown-emscripten
> +
> +
> +You can also use the CMake build system to build libxmp, which requires
> +cmake versions 3.2 or newer ( https://cmake.org )
> +
>  
>  To build for Windows using Visual Studio, use Makefile.vc:
>  
>    nmake -f Makefile.vc   (read/edit Makefile.vc as necessary.)
>  
> +
>  To build for Windows using OpenWatcom, use Makefile.w32:
>  
>    wmake -f Makefile.w32  (read/edit Makefile.w32 as necessary.)
>  
> +
>  To build for OS/2 using OpenWatcom, use Makefile.os2:
>  
>    wmake -f Makefile.os2  (read/edit Makefile.os2 as necessary.)
> ```
