### ISSUE TITLE
more -Wunused-but-set-variable warnings

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#469]
The following shows up in CI emscripten build jobs:
```
src/loaders/st_load.c:211:6: warning: variable 'smp_size' set but not used [-Wunused-but-set-variable]
        int smp_size;
            ^

src/loaders/ims_load.c:150:9: warning: variable 'smp_size' set but not used [-Wunused-but-set-variable]
    int smp_size;
        ^

src/loaders/prowizard/p61a.c:36:9: warning: variable 'ssize' set but not used [-Wunused-but-set-variable]
    int ssize = 0;
        ^
src/loaders/prowizard/p61a.c:566:9: warning: variable 'ssize' set but not used [-Wunused-but-set-variable]
    int ssize;
        ^

src/mix_paula.c:133:1: warning: parameter 'vr' set but not used [-Wunused-but-set-parameter]
MIXER(mono_a500)
^
src/mixer.h:18:25: note: expanded from macro 'MIXER'
        int count, int vl, int vr, int step, int ramp, int delta_l, int delta_r)
                               ^
src/mix_paula.c:140:1: warning: parameter 'vr' set but not used [-Wunused-but-set-parameter]
MIXER(mono_a500_filter)
^
src/mixer.h:18:25: note: expanded from macro 'MIXER'
        int count, int vl, int vr, int step, int ramp, int delta_l, int delta_r)
                               ^

src/depackers/uncompress.c:74:7: warning: variable 'bytes_in' set but not used [-Wunused-but-set-variable]
        long bytes_in;                  /* Total number of byte from input */
             ^
```

**Comment by sezero** [comment]
We also have this:
```
src/depackers/bunzip2.c: In function 'get_next_block':
src/depackers/bunzip2.c:129:21: warning: variable 'hufGroup' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
  struct group_data *hufGroup;
                     ^
```

**Comment by AliceLR** [comment]
I noticed these while checking CI logs for the -Wextra patch—I'll check into them and report back.

**Comment by AliceLR** [comment]
> ```
> src/loaders/st_load.c:211:6: warning: variable 'smp_size' set but not used [-Wunused-but-set-variable]
>         int smp_size;
>             ^
> 
> src/loaders/ims_load.c:150:9: warning: variable 'smp_size' set but not used [-Wunused-but-set-variable]
>     int smp_size;
>         ^
> 
> src/loaders/prowizard/p61a.c:36:9: warning: variable 'ssize' set but not used [-Wunused-but-set-variable]
>     int ssize = 0;
>         ^
> src/loaders/prowizard/p61a.c:566:9: warning: variable 'ssize' set but not used [-Wunused-but-set-variable]
>     int ssize;
>         ^

These are more remnants of code that was either moved to test functions or ProWizard code that is no longer relevant, easy fixes.

>```
> src/mix_paula.c:133:1: warning: parameter 'vr' set but not used [-Wunused-but-set-parameter]
> MIXER(mono_a500)
> ^
> src/mixer.h:18:25: note: expanded from macro 'MIXER'
>         int count, int vl, int vr, int step, int ramp, int delta_l, int delta_r)
>                                ^
> src/mix_paula.c:140:1: warning: parameter 'vr' set but not used [-Wunused-but-set-parameter]
> MIXER(mono_a500_filter)
> ^
> src/mixer.h:18:25: note: expanded from macro 'MIXER'
>         int count, int vl, int vr, int step, int ramp, int delta_l, int delta_r)
>                                ^
>```

More useless warnings a la `-Wunused-parameter`, ew.

>```
> src/depackers/uncompress.c:74:7: warning: variable 'bytes_in' set but not used [-Wunused-but-set-variable]
>         long bytes_in;                  /* Total number of byte from input */
>              ^
> ```

Not sure what's up with this one, but it can be commented out same as `bytes_out`.

> ```
> src/depackers/bunzip2.c: In function 'get_next_block':
> src/depackers/bunzip2.c:129:21: warning: variable 'hufGroup' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
>   struct group_data *hufGroup;
>                      ^
> ```

"Checking for an EOF state is hard so we're going to use `setjmp`/`longjmp` pseudo-exceptions! We don't care that the fix for potentially clobbered pointers is making them `volatile`, which makes our code slower in the long run!"
