### ISSUE TITLE
cmake: documentation not generated

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#477]
As title says. We should do this (possibly similar to libmikmod, i.e.
disabled silently when the tools aren't found.)

@Wohlstand can you do this, or should I make the effort?

**Comment by Wohlstand** [comment]
I'll try, however, first off I need to check how it's doing. Also, when the case tool is missing, I'll pop up the warning on the fact the important tool is absent and documentation will NOT be generated.

**Comment by Wohlstand** [comment]
I Will try something in the evening (UTC+3), right now I am busy with my main job.

**Comment by Wohlstand** [comment]
Okay, I'll try some tomorrow, this day sucks... Tomorrow I should have more time and energy for the work

**Comment by sezero** [comment]
Any progress?

**Comment by Wohlstand** [comment]
Recently I tried to implement some, and I almost finished my work, I will need to polish a bit until I will send an update, I was busy on real-life tasks and other works, thanks for reminding me, I'll try to resume this work as soon as possible.
