### ISSUE TITLE
Double amplification by default?

### ISSUE THREAD

**Issue by AliceLR** [libxmp/libxmp#499]
Why is the default amplification level 2x? This makes [Pandora's Box (FB Mix)](https://modarchive.org/index.php?request=view_by_moduleid&query=41557) clip very badly by default.

common.h line 92:
```C
#define DEFAULT_AMPLIFY	1
```
```
   -a --amplify {0|1|2|3} Amplification factor: 0=Normal, 1=x2, 2=x4, 3=x8
```

edit: it seems like this might just be because old modules are relatively quiet and Modplug 1.16 and OpenMPT do some weird automatic gain reduction for loud modules like this one? i.e. possibly not an issue.

**Comment by AliceLR** [comment]
https://github.com/libxmp/libxmp/commit/6d175008bca9c6df5fe7c0e9c5cfd6111678f786 ???????????????????????????????????????????????????????????????????????????????????????????????????!

**Comment by sagamusix** [comment]
MPT had rather low mix levels, or to be precise, the *default* mix levels were low. There was a pre-amp setting that applied to all modules played in MPT, but its value was not stored in module files, so all you can do is guess how loud the user wanted their module to sound! In later OpenMPT versions the gain is fixed (identical to Schism Tracker's gain), but for files made with old MPT it will keep using the original levels (which are still user-configurable through the "sample pre-amp" setting). So if the volume of a module made with the original MPT is too low or too high, there's probably not much that can be done.

> automatic gain reduction

This exists but it's disabled by default.

**Comment by AliceLR** [comment]
Interesting—so this module playing back at a reasonable volume in OpenMPT is a playback quirk specifically for classic Modplug modules (which the module in question is). So *probably* no issue on libxmp's part, unless somehow libxmp could preemptively detect really loud modules and tweak the amplification factor (sounds annoying to implement and only helps modules with an absurd number of channels...).

**Comment by sagamusix** [comment]
I suppose that libxmp could reduce the amplification for MPT modules a bit, assuming that they were made with default pre-amp settings in MPT. Of course that's not perfect either. XMPlay/BASS auto-normalize modules, which is also an optional feature I want to have for libopenmpt (in fact I have a 90% ready implementation somewhere...). This also helps with modules like this one.

**Comment by AliceLR** [comment]
Closing since this one's not really a bug.
