### ISSUE TITLE
Building libxmp-lite with cmake

### ISSUE THREAD

**Issue by r0ptr** [libxmp/libxmp#502]
Hello!

I've been trying to figure out if it's possible to build libxmp-lite with cmake, without relying on autoconf, make and friends earlier. So far, the only way I found is exactly by using these tools, such that a `libxmp-list-stagedir` is generated in the source-root, and within it, a directory name `libxmp-lite-4.5.0`, which contains all the pieces that are otherwise missing from `{SOURCE_ROOT}/lite`. When I add that directory with `add_subdirectory` in my cmake project, it is indeed buildable, but this whole process seems clunky, and relies on a lot of tools, before CMake is usable. I somehow think that I oversaw something and that there might be a more convenient way after all to include libxmp-lite in a project. Any hints on how to achieve this?

Thanks!

**Comment by sezero** [comment]
To my best knowledge, libxmp-lite is only meant to be buildable from a
release tarball and not from git. To do that, do the following:
```
./autogen.sh && make -f Makefile.lite [generates the tar.gz file]
tar xfz libxmp-lite-<version>.tar.gz  [extracts the tar.gz file.]
```
Then, cd into `libxmp-lite-<version>` directory and build using cmake or
autotools.

**Comment by r0ptr** [comment]
Thanks, that's ok, but I must say this does make it hard to embed libxmp-lite as a source dependency into other projects, as in such cases these dependencies are included either as a git submodule, or downloaded with FetchContent in cmake, or a similar mechanism, and they should be buildable as-is. Any hope this might hange in the future?

**Comment by sezero** [comment]
Me myself have no plans for it, others might..  Well-tested patches would be welcome.

**Comment by mmontag** [comment]
Hmm... I thought @Wohlstand mentioned that building lite version was possible with Cmake: https://github.com/libxmp/libxmp/pull/415 but maybe it requires some extra maneuvers out of the box. Is that what you guys are talking about?

**Comment by sezero** [comment]
No. The problem here is the lack of ability to build the lite version directly from the git repo, which isn't supported not only by the cmake build system but also by autotools and other standalone makefiles. Closing this as WONTFIX.

**Comment by Wohlstand** [comment]
At my first CMake build implementation (before I started campaing on sending it to here) I made the direct ability to build both lite and full versions from out the box. However, there was a request to me to have separated build for lite, because both full and lite versions intended to be released as separated independent tarballs. From the git version you can only regenerate the lite version tarball and then unpack it anywhere and build lite version by cmake inside it.
