### ISSUE TITLE
muse.c should be moved out of depackers

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#506]
As the title says - without that, gal4/gal5 loaders are useless.

**Comment by sezero** [comment]
Related issue: https://github.com/libxmp/libxmp/issues/387

**Comment by AliceLR** [comment]
Even though I proposed this I'm having a hard time seeing what the clean implementation of it is—maybe a muse_load.c and move tinfl to core code? Would it be better to have a "light" depackers mode where we keep the MOD-specific depackers (similar to how libmodplug and MikMod handle depackers) and get rid of the external/general/copyleft depackers?

**Comment by sezero** [comment]
General idea sounds good to me.

> edit: I mean specifically these ones:
> 
>  MMCMP (PD? MIT???)

_Should_ be PD (all implementations around are lifted from libmodplug)

> Muse (trivial to rewrite as permissive with tinfl.c).
> PowerPacker (PD)
> StoneCracker (PD)
> XPK-SQSH (MIT)

Yes

> MAYBE ARC/ArcFS after I rewrite them since support for these seems uncommon at best, but a TON of modules from the RISC OS scene are packed in them.

Sound nice.

The ones to be left out are unzip, gunzip, bunzip, unlha, unlzx, unxz (the
ones that we actually build): My general idea of them is they should be handled
by the player -- i.e. libxmp5 maybe?

Also, maybe we can disable depackers by default, and add a big fat notice
to configury that with depackers enabled the library is (L)GPL'ed ??

**Comment by AliceLR** [comment]
To clarify, I didn't mean disabling a bunch of depackers as a *default* option, but as an option to strip the library down a little bit without getting rid of required functionality like MUSE (if needed).

I don't think the LGPL licensed code will be much of an "issue" in the long term, since the worst of it has already been replaced (KZip) or is queued up for replacement (nomarch). That leaves what, bunzip2 and LHA (and LZX which is Amiga only)?

**Comment by AliceLR** [comment]
Ugh, thinking about this more, it seems like there's four different states for the depackers we'd want to target in our current situation (emphasis on the relevant case for this ticket):

* All depackers, including LGPL and external. (`--enable-depackers-lgpl` or something)
* All depackers except LPGL and external. This seems like the most sane default state, particularly after more depackers get updated. (`--enable-depackers`)
* *MUSE and other MOD-specific or niche depackers only*. This seems like what would be the most useful for users who already handle general depacking. I don't think we should throw anyone relying on the general depackers under the bus, though, so this maybe shouldn't be default. (`--enable-depackers-lite` or something?)
* No depackers at all. Mostly only useful for libxmp-lite or if libxmp is contrib code and you're already stripping out components like the J2B loaders code I think? (MegaZeux does that...) (`--disable-depackers`)

So we're back to getting those first two cases as close to each other as reasonably possible to reduce the number of compile time settings... ugh. But aside from that, does this sound like an acceptable solution for this issue?

**Comment by sezero** [comment]
Here is a quick workaround for `MUSE`, minus the obvious files moving around.
The FIXME is that I don't have a cheap solution for the test procedure to read the
module name.
```c
#include "loader.h"
#include "../miniz.h"

static int muse_test(HIO_HANDLE *, char *, const int);
static int muse_load(struct module_data *, HIO_HANDLE *, const int);

const struct format_loader libxmp_loader_muse = {
	"MUSE container",
	muse_test,
	muse_load
};

static int muse_test(HIO_HANDLE * f, char *t, const int start)
{
	uint8 in[24];
	uint32 r;

	if (hio_read(in, 1, 24, f) != 24) {
		return -1;
	}
	if (memcmp(in, "MUSE", 4) != 0) {
		return 0;
	}
	r = readmem32b(in + 4);
	/* MOD2J2B uses 0xdeadbabe */
	if (r != 0xdeadbeaf && r != 0xdeadbabe) {
		return -1;
	}
	if (t) {
		*t = '\0'; /* FIXME */
	}
	return 0;
}

static int muse_load(struct module_data *m, HIO_HANDLE *f, const int start)
{
	long in_buf_size;
	void *pCmp_data, *pOut_buf;
	size_t pOut_len;
	HIO_HANDLE *tmp;
	int err;

	in_buf_size = hio_size(f);
	if (in_buf_size < 24 || in_buf_size >= LIBXMP_DEPACK_LIMIT) {
		D_(D_CRIT "bad file size");
		return -1;
	}
	if (hio_seek(f, 24, SEEK_SET) < 0) {
		D_(D_CRIT "hio_seek() failed");
		return -1;
	}

	in_buf_size -= 24;
	pCmp_data = (uint8 *)malloc(in_buf_size);
	if (!pCmp_data) {
		D_(D_CRIT "Out of memory");
		return -1;
	}
	if (hio_read(pCmp_data, 1, in_buf_size, f) != in_buf_size) {
		D_(D_CRIT "Failed reading input file");
		free(pCmp_data);
		return -1;
	}

	pOut_buf = tinfl_decompress_mem_to_heap(pCmp_data, in_buf_size, &pOut_len, TINFL_FLAG_PARSE_ZLIB_HEADER);
	if (!pOut_buf) {
		D_(D_CRIT "tinfl_decompress_mem_to_heap() failed");
		free(pCmp_data);
		return -1;
	}
	free(pCmp_data);

	tmp = hio_open_mem(pOut_buf, pOut_len, 1);
	if (!tmp) { /* ehh.. */
		free(pOut_buf);
		return -1;
	}
	err = libxmp_loader_gal5.test(tmp, NULL, 0);
	hio_seek(tmp, 0, SEEK_SET);
	if (err == 0) {
		err = libxmp_loader_gal5.loader(m, tmp, 0);
	} else {
		err = libxmp_loader_gal4.test(tmp, NULL, 0);
		hio_seek(tmp, 0, SEEK_SET);
		if (err == 0) {
			err = libxmp_loader_gal4.loader(m, tmp, 0);
		}
	}
	hio_close(tmp);

	return err;
}
```

**Comment by sezero** [comment]
`test_depack_j2b` fails md5 compare - why?..
