### ISSUE TITLE
issues with mmcmp depacker

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#517]
Originally noted by https://github.com/libxmp/libxmp/issues/516#issuecomment-1000755649 :

This file that makes valgrind to report uninitialized read warnings when one changes calloc to malloc at line 346 for outbuf.buf, whereas libmikmod is OK: [FLYBY.zip](https://github.com/libxmp/libxmp/files/7773771/FLYBY.zip)

And this one fails loading with libxmp (with PR #516 or before it), whereas libmikmod loads it: [EVERSMOK.zip](https://github.com/libxmp/libxmp/files/7773754/EVERSMOK.zip)

**Comment by sezero** [comment]
Here are the valgrind warnings with malloc instead of calloc:
```
==16007== Syscall param write(buf) points to uninitialised byte(s)
==16007==    at 0x9A0CFB: ??? (syscall-template.S:82)
==16007==    by 0x93A05F: _IO_file_xsputn@@GLIBC_2.1 (fileops.c:522)
==16007==    by 0x92FBDD: fwrite (iofwrite.c:45)
==16007==    by 0x4071A9E: decrunch_mmcmp (mmcmp.c:444)
==16007==    by 0x40708AF: libxmp_decrunch (depacker.c:295)
==16007==    by 0x40256F6: xmp_load_module (load.c:371)
==16007==    by 0x804B180: main (main.c:407)
==16007==  Address 0x40deb72 is 298 bytes inside a block of size 772,338 alloc'd
==16007==    at 0x40072B2: malloc (vg_replace_malloc.c:270)
==16007==    by 0x407176B: decrunch_mmcmp (mmcmp.c:346)
==16007==    by 0x40708AF: libxmp_decrunch (depacker.c:295)
==16007==    by 0x40256F6: xmp_load_module (load.c:371)
==16007==    by 0x804B180: main (main.c:407)
```

**Comment by AliceLR** [comment]
I don't think the parts of the dest buffer that aren't being written to are an issue—MMCMP streams can arbitrarily seek all over the place and probably intentionally skip stretches of 0 bytes. `GlobalAllocPtr` in libmodplug uses `malloc`+`memset` (???) and `MikMod_malloc` uses `calloc`.

**Comment by AliceLR** [comment]
here's every sub block in FLYBY.IT as seen by libxmp, rearranged to be in order. It looks like it really does seek around to wherever it wants to, but there aren't gaps. It's writing block 1 a byte short. Do the other libraries do this too when modified to not `calloc` the buffer?

```
block  0 sub 0 start:0      end:48 (size:48)
block  1 sub 0 start:48     end:299 (size:251)
block 23 sub 0 start:299    end:333 (size:34)
block  2 sub 0 start:333    end:1853 (size:1520)
block  3 sub 0 start:1853   end:5728 (size:3875)
block  5 sub 0 start:5728   end:207968 (size:202240)
block  6 sub 0 start:207968 end:227200 (size:19232)
block  7 sub 0 start:227200 end:242464 (size:15264)
block  8 sub 0 start:242464 end:251805 (size:9341)
block  9 sub 0 start:251805 end:313245 (size:61440)
block 10 sub 0 start:313245 end:333650 (size:20405)
block  4 sub 0 start:333650 end:336460 (size:2810)
block 11 sub 0 start:336460 end:377684 (size:41224)
block 12 sub 0 start:377684 end:423346 (size:45662)
block 22 sub 0 start:423346 end:498908 (size:75562)
block 13 sub 0 start:498908 end:510119 (size:11211)
block 14 sub 0 start:510119 end:529335 (size:19216)
block 15 sub 0 start:529335 end:579335 (size:50000)
block 16 sub 0 start:579335 end:609349 (size:30014)
block 17 sub 0 start:609349 end:635015 (size:25666)
block 18 sub 0 start:635015 end:658755 (size:23740)
block 19 sub 0 start:658755 end:682338 (size:23583)
block 20 sub 0 start:682338 end:732338 (size:50000)
block 21 sub 0 start:732338 end:772338 (size:40000)
```

**Comment by AliceLR** [comment]
Okay, the issue with EVERSMOK.S3M is really dumb: it tries to unconditionally read 256 bytes for a table at the start of the block and then tries to seek *back* to the end of the table. If the initial 256 byte read fails to read exactly 256 bytes, the file gets rejected. EVERSMOK.S3M ends with a 32 byte block.

**Comment by sezero** [comment]
> I don't think the parts of the dest buffer that aren't being written to are an issue—MMCMP streams can arbitrarily seek all over the place and probably intentionally skip stretches of 0 bytes. `GlobalAllocPtr` in libmodplug uses `malloc`+`memset` (???) and `MikMod_malloc` uses `calloc`.

Replaced all `MikMod_malloc` in libmikmod's mmcmp.c to plain `malloc`, no valgrind warnings.

**Comment by sezero** [comment]
> Okay, the issue with EVERSMOK.S3M is really dumb: it tries to unconditionally read 256 bytes for a table at the start of the block and then tries to seek _back_ to the end of the table. If the initial 256 byte read fails to read exactly 256 bytes, the file gets rejected. EVERSMOK.S3M ends with a 32 byte block.

#518 fixes EVERSMOK.S3M playback

**Comment by sezero** [comment]
>  `GlobalAllocPtr` in libmodplug uses `malloc`+`memset` (???)

That's because of `GHND` flag in calling `GlobalAllocPtr`, which means `GMEM_MOVEABLE | GMEM_ZEROINIT`, see 
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-globalalloc

**Comment by sezero** [comment]
Pushed b2451fbf3b0422 to go back from calloc to malloc the outbuf.buf for now

**Comment by AliceLR** [comment]
Still not sure what's going on with FLYBY just from looking at the code. The decompression logic looks essentially identical between libxmp, libmodplug, and MikMod. Using `malloc` there is a bad idea because, as mentioned before, MMCMP can instruct the decompressor to seek wherever it wants, so gaps are a possibility in valid streams.

**Comment by sezero** [comment]
> Still not sure what's going on with FLYBY just from looking at the code. The decompression logic looks essentially identical between libxmp, libmodplug, and MikMod. Using `malloc` there is a bad idea because, as mentioned before, MMCMP can instruct the decompressor to seek wherever it wants, so gaps are a possibility in valid streams.

I tend to disagree? We are writing the final buffer which is supposed to have no gaps.
I fwrite the temporary memory buffer to a file in libmikmod, and the file is identical to
the original FlyBy.it itself.

**Comment by AliceLR** [comment]
You can trivially construct a MMCMP file with two blocks spaced apart, and the fuzzers *will do exactly that* and I'll have to fix it anyway.

**Comment by sezero** [comment]
OK, but how will that prevent outputing gaps from a valid mmcmp?

**Comment by AliceLR** [comment]
It won't. It will prevent them from containing uninitialized data.

**Comment by sezero** [comment]
Yes. What I'm saying is let's keep it as malloc until we figure out with the flyby situation.

**Comment by sezero** [comment]
For the record, I used mmcmp.exe from here:
http://cd.textfiles.com/scene96-2/programs/mmcmp134/
.. to compress unreal's FlyBy.it (extracted from the umx
using [umr](https://github.com/sezero/umr)).

**Comment by AliceLR** [comment]
Doing maintenance work on my Fedora VM and then I can get back to this. Due to the decompression algorithms being implemented nearly exactly the same, I suspect that this behavior does exist in both libmodplug and MikMod, though, and for some reason (maybe the `fwrite`) is only getting detected in libxmp by Valgrind. Maybe MMCMP can intentionally emit short blocks?

**Comment by sezero** [comment]
Mikmod: not impossible (remember to test by changing all `MikMod_malloc` in mmcmp.c to plain `malloc`)

libmodplug: just tested with my fork, changed calloc to plain malloc, valgrind reports a lot of uninitialized reads (with and without the malloc'ed buffer aligned to 16)

**Comment by AliceLR** [comment]
With my local (bugfixed) libmodplug, FLYBY.IT just fails to load? Huh...

**Comment by AliceLR** [comment]
There's *definitely* something similar going on with libmodplug according to MemorySanitizer. Haven't figured out how to get it to print the offset into the allocation where the uninitialized byte(s) are, though:

```
[a@localhost fuzz]$ ./load FLYBY.IT 
==2983==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5523f1 in CSoundFile::ReadIT(unsigned char const*, unsigned int) /home/a/libmodplug/fuzz/../src/load_it.cpp:329:25
    #1 0x5c0366 in CSoundFile::Create(unsigned char const*, unsigned int) /home/a/libmodplug/fuzz/../src/sndfile.cpp:142:9
    #2 0x5b8dd3 in ModPlug_Load /home/a/libmodplug/fuzz/../src/modplug.cpp:88:24
    #3 0x4a7d82 in main /home/a/libmodplug/fuzz/load.cpp:57:28
    #4 0x7f4ad235955f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)
    #5 0x7f4ad235960b in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2d60b)
    #6 0x424514 in _start (/home/a/libmodplug/fuzz/load+0x424514)

  Uninitialized value was stored to memory at
    #0 0x45496a in __msan_memcpy.part.0 msan_interceptors.cpp.o
    #1 0x54db93 in CSoundFile::ReadIT(unsigned char const*, unsigned int) /home/a/libmodplug/fuzz/../src/load_it.cpp:261:2
    #2 0x5c0366 in CSoundFile::Create(unsigned char const*, unsigned int) /home/a/libmodplug/fuzz/../src/sndfile.cpp:142:9
    #3 0x5b8dd3 in ModPlug_Load /home/a/libmodplug/fuzz/../src/modplug.cpp:88:24
    #4 0x4a7d82 in main /home/a/libmodplug/fuzz/load.cpp:57:28
    #5 0x7f4ad235955f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)

  Uninitialized value was created by a heap allocation
    #0 0x454c12 in malloc (/home/a/libmodplug/fuzz/load+0x454c12)
    #1 0x5b1d69 in GlobalAllocPtr(unsigned int, unsigned long) /home/a/libmodplug/fuzz/../src/libmodplug/stdafx.h:109:27
    #2 0x5b1d69 in MMCMP_Unpack(unsigned char const**, unsigned int*) /home/a/libmodplug/fuzz/../src/mmcmp.cpp:178:25
    #3 0x5c021c in CSoundFile::Create(unsigned char const*, unsigned int) /home/a/libmodplug/fuzz/../src/sndfile.cpp:138:17
    #4 0x5b8dd3 in ModPlug_Load /home/a/libmodplug/fuzz/../src/modplug.cpp:88:24
    #5 0x4a7d82 in main /home/a/libmodplug/fuzz/load.cpp:57:28
    #6 0x7f4ad235955f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/a/libmodplug/fuzz/../src/load_it.cpp:329:25 in CSoundFile::ReadIT(unsigned char const*, unsigned int)
Exiting
```

**Comment by sezero** [comment]
I found an old version of a fork of mine (not online anymore), this doesn't report errors for me (after changing GlobalAllocPtr to plain malloc, of course): [mmcmp.cpp.zip](https://github.com/libxmp/libxmp/files/7775353/mmcmp.cpp.zip)

**Comment by sezero** [comment]
I reconstructed my old mmcmp version in my current fork in a new sezero-mmcmp branch:
https://github.com/sezero/libmodplug/tree/sezero-mmcmp
Even if you replace the `calloc`s with `malloc` and remove the extra alignment bytes from
them, valgrind doesn't emit any warnings.

Maybe this will help with things.

**Comment by AliceLR** [comment]
Same output from MemorySanitizer with the mmcmp.cpp from your branch. It seems like Valgrind just can not detect this consistently:
```
[a@localhost fuzz]$ ./load FLYBY.IT 
==3293==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5523f1 in CSoundFile::ReadIT(unsigned char const*, unsigned int) /home/a/libmodplug/fuzz/../src/load_it.cpp:329:25
    #1 0x5c0376 in CSoundFile::Create(unsigned char const*, unsigned int) /home/a/libmodplug/fuzz/../src/sndfile.cpp:142:9
    #2 0x5b8de3 in ModPlug_Load /home/a/libmodplug/fuzz/../src/modplug.cpp:88:24
    #3 0x4a7d82 in main /home/a/libmodplug/fuzz/load.cpp:57:28
    #4 0x7fe2cc27555f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)
    #5 0x7fe2cc27560b in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2d60b)
    #6 0x424514 in _start (/home/a/libmodplug/fuzz/load+0x424514)

  Uninitialized value was stored to memory at
    #0 0x45496a in __msan_memcpy.part.0 msan_interceptors.cpp.o
    #1 0x54db93 in CSoundFile::ReadIT(unsigned char const*, unsigned int) /home/a/libmodplug/fuzz/../src/load_it.cpp:261:2
    #2 0x5c0376 in CSoundFile::Create(unsigned char const*, unsigned int) /home/a/libmodplug/fuzz/../src/sndfile.cpp:142:9
    #3 0x5b8de3 in ModPlug_Load /home/a/libmodplug/fuzz/../src/modplug.cpp:88:24
    #4 0x4a7d82 in main /home/a/libmodplug/fuzz/load.cpp:57:28
    #5 0x7fe2cc27555f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)

  Uninitialized value was created by a heap allocation
    #0 0x454c12 in malloc (/home/a/libmodplug/fuzz/load+0x454c12)
    #1 0x5b1d79 in GlobalAllocPtr(unsigned int, unsigned long) /home/a/libmodplug/fuzz/../src/libmodplug/stdafx.h:109:27
    #2 0x5b1d79 in MMCMP_Unpack(unsigned char const**, unsigned int*) /home/a/libmodplug/fuzz/../src/mmcmp_orig.cpp:178:25
    #3 0x5c022c in CSoundFile::Create(unsigned char const*, unsigned int) /home/a/libmodplug/fuzz/../src/sndfile.cpp:138:17
    #4 0x5b8de3 in ModPlug_Load /home/a/libmodplug/fuzz/../src/modplug.cpp:88:24
    #5 0x4a7d82 in main /home/a/libmodplug/fuzz/load.cpp:57:28
    #6 0x7fe2cc27555f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/a/libmodplug/fuzz/../src/load_it.cpp:329:25 in CSoundFile::ReadIT(unsigned char const*, unsigned int)
Exiting
```

**Comment by sezero** [comment]
> edit: fixed my crappy test system. Your branch does not generate the error.

OK :)

> edit: here's the loader I'm using (junk around the compilation commands because Clang throws a fit otherwise and I didn't feel like diagnosing it). To get the above MemorySanitizer errors, just comment out the part of `GlobalAllocPtr` in stdafx.h that performs `memset`.

My branches don't use `GlobalAllocPtr` - I replaced its only a few uses with calloc, and now in the new `sezero-mmcmp` branch, the `calloc`s are replaced with `malloc`

**Comment by AliceLR** [comment]
Okay, found it, thanks. It's that stupid right shift in 16 bit compressed truncating a byte of the block.

**Comment by sezero** [comment]
> Okay, found it, thanks. It's that stupid right shift in 16 bit compressed blocks truncating a byte of the block.

Um? Can you point to it?

**Comment by AliceLR** [comment]
[This one in libmodplug](https://github.com/Konstanty/libmodplug/blob/master/src/mmcmp.cpp#L225) and [the corresponding one in libxmp](https://github.com/libxmp/libxmp/blob/master/src/depackers/mmcmp.c#L171). Your patch adds 2 instead, which is why that byte gets initialized.

Who knows why MMCMP emits 16-bit compressed blocks with odd lengths... oh well.

**Comment by AliceLR** [comment]
Patch: #519

**Comment by sezero** [comment]
I was hasty to apply the patch. With calloc changed to malloc, I get:
```
==592== Syscall param write(buf) points to uninitialised byte(s)
==592==    at 0x9A0CFB: ??? (syscall-template.S:82)
==592==    by 0x93A05F: _IO_file_xsputn@@GLIBC_2.1 (fileops.c:522)
==592==    by 0x92FBDD: fwrite (iofwrite.c:45)
==592==    by 0x4071AC6: decrunch_mmcmp (mmcmp.c:449)
==592==    by 0x40708DF: libxmp_decrunch (depacker.c:295)
==592==    by 0x4025726: xmp_load_module (load.c:371)
==592==    by 0x804B180: main (main.c:407)
==592==  Address 0x40e0b1c is 300 bytes inside a block of size 772,338 alloc'd
==592==    at 0x40072B2: malloc (vg_replace_malloc.c:270)
==592==    by 0x407179B: decrunch_mmcmp (mmcmp.c:353)
==592==    by 0x40708DF: libxmp_decrunch (depacker.c:295)
==592==    by 0x4025726: xmp_load_module (load.c:371)
==592==    by 0x804B180: main (main.c:407)
```

**Comment by sezero** [comment]
And my eyes are burning, will have to sleep soon.

**Comment by AliceLR** [comment]
OK. Will look further into this... that seems like it should have fixed it, though.

**Comment by sezero** [comment]
The old `298 bytes` vs the new `300 bytes` might be the clue. (Can't think straight right now, though.)

**Comment by AliceLR** [comment]
> The old `298 bytes` vs the new `300 bytes` might be the clue. (Can't think straight right now, though.)

No, I think you're correct—the 16-bit depacking bug *is* fixed, but there is likely another bug related to block 23 (which starts at 299).

**Comment by AliceLR** [comment]
Okay, I think this one is entirely libxmp-specific: it wasn't seeking to the start of literal sub blocks before copying before the recent patches.

**Comment by sezero** [comment]
Deleting this ticket: the attached mods may result in copyright crapola.
