### ISSUE TITLE
uninitialized warning at -O3

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#554]
As per title:
```
src/mixer.c: In function 'libxmp_mixer_softmixer':
src/mixer.c:483: warning: 'loop_data._16bit' may be used uninitialized in this function
src/mixer.c:483: warning: 'loop_data.first_loop' may be used uninitialized in this function
src/mixer.c:483: warning: 'loop_data.end' may be used uninitialized in this function
src/mixer.c:483: warning: 'loop_data.start' may be used uninitialized in this function
src/mixer.c:483: warning: 'loop_data.sptr' may be used uninitialized in this function
```

**Comment by sezero** [comment]
BTW, this was with gcc-4.4.7 of RedHat (CentOS 6.10 to be exact.)

**Comment by AliceLR** [comment]
I think this is probably a lie from older GCC versions with broken inlining warnings. Those fields are only accessed in two functions and the reads are guarded with `ld->active`. This could be """""fixed""""" with a `memset` right after `libxmp_mixer_prepare` (but also those versions of CentOS and GCC are no longer supported (also CentOS is dead (good thing I didn't update my VPSes to CentOS 8 (thanks Red Hat (lol 🖕))))).

**Comment by AliceLR** [comment]
Eh, it's only 40 bytes and will probably cap out at 72 after stereo samples/sinc interpolation are added, whatever...
```diff
diff --git a/src/mixer.c b/src/mixer.c
index 11471047..6c0c9ed8 100644
--- a/src/mixer.c
+++ b/src/mixer.c
@@ -523,6 +523,7 @@ void libxmp_mixer_softmixer(struct context_data *ctx)
 #endif
 
 	libxmp_mixer_prepare(ctx);
+	memset(&loop_data, 0, sizeof(loop_data));
 
 	for (voc = 0; voc < p->virt.maxvoc; voc++) {
 		int c5spd, rampsize, delta_l, delta_r;
```

**Comment by sezero** [comment]
We can just ignore: it only shows itself at -O3.

**Comment by AliceLR** [comment]
> We can just ignore: it only shows itself at -O3.

I *think* libxmp is clean enough/its undefined behavior has been fixed enough that -O3 would actually be viable the default optimization level, though we'd probably want a GCC version cutoff since -O3 apparently used to be pretty broken (not sure what a good cutoff would be). I've been using a subset of libxmp at -O3 for several in my MegaZeux fork with no issues.

**Comment by sezero** [comment]
Speaking of warnings, cmake emits stupid `-Wunused-function` warnings for
two `mz_zip_string_equal` and `mz_zip_filename_compare` inlines.

**Comment by sezero** [comment]
Pushed https://github.com/libxmp/libxmp/commit/db5f9a80ec6df7b9b4899588e0fc26331f5ddc9f to shutup clang.

As for bogus uninitialized warning at -O3: seems only with gcc4.4: I'll ignore and close this, yes?

**Comment by sezero** [comment]
Well, I'll ignore this. Closing.
