### ISSUE TITLE
Android: Unable to compile with CMake

### ISSUE THREAD

**Issue by knight-ryu12** [libxmp/libxmp#583]
Android-JNI now have support with CMake. but seems it require some options regards of __android_log_xxx function.

Adding -llog to LINK_FLAG solves situation, but I don't know what's the suitable way to implement this.

**Comment by sezero** [comment]
This is for `DEBUG` builds, yes?

@Wohlstand, have you tried this?

**Comment by Wohlstand** [comment]
For me it builds fine, I do build the project as a static library and I do link `-llog` library at my project side as I do use a built-in Android logger for my needs. The libxmp when has built using debug mode will enable logging. It's a usual case when static libraries require to manually link all their dependencies. There is only a case when you build a shared library and linking it doesn't require you to link any dependencies.

**Comment by sezero** [comment]
WelI, as I understand it, @knight-ryu12 wants to build a shared lib and in debug mode: so where best to add the necessary `-llog` in the cmake scripts? (should be needed in both full and lite versions.)

**Comment by knight-ryu12** [comment]
Yes. probably better to use ndkBuild, but CMake would be much nicer since they have support for it.

**Comment by sezero** [comment]
OK.  @knight-ryu12: Does the following patch resolve your issue?

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 985d045..be03444 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -127,6 +127,9 @@ if(BUILD_SHARED)
     if(LIBM_REQUIRED)
         target_link_libraries(xmp_shared PUBLIC ${LIBM_LIBRARY})
     endif()
+    if(ANDROID AND CMAKE_BUILD_TYPE_LOWER STREQUAL "debug")
+        target_link_libraries(xmp_shared PRIVATE log)
+    endif()
 endif()
 
 
diff --git a/lite/CMakeLists.txt b/lite/CMakeLists.txt
index a4e801d..c4cbbf0 100644
--- a/lite/CMakeLists.txt
+++ b/lite/CMakeLists.txt
@@ -119,6 +119,9 @@ if(BUILD_SHARED)
     if(LIBM_REQUIRED)
         target_link_libraries(xmp_lite_shared PUBLIC ${LIBM_LIBRARY})
     endif()
+    if(ANDROID AND CMAKE_BUILD_TYPE_LOWER STREQUAL "debug")
+        target_link_libraries(xmp_shared PRIVATE log)
+    endif()
 endif()
 
 
```

**Comment by sezero** [comment]
No response from @knight-ryu12 so I applied the patch and closed this.

If there are still issues, please drop a note here.

**Comment by knight-ryu12** [comment]
Sorry, real life got caught up. But yes I got it to compiile. thanks.
