### ISSUE TITLE
[Question] How to properly retrieve the number of tracks in the song?

### ISSUE THREAD

**Issue by Wohlstand** [libxmp/libxmp#603]
Hello!

At my library (where I use libXMP), I do use the `music->fi.virt_channels` field to retrieve a number of channels (I need that to pass into the UI of my player to allow the user to mute each track of the song individually). However, one of the users reported that there is an IT file with 16 tracks programmed, and reported 144 tracks. Should I use a different way to retrieve a number of tracks in the song to report them correctly?

The test file: [pm-shiver-mountain.it.gz](https://github.com/libxmp/libxmp/files/9295495/pm-shiver-mountain.it.gz)

**Comment by AliceLR** [comment]
The correct field *should* be `xmp_module::chn`—for IT modules, `xmp_frame_info::virt_channels` will report that number +128 because libxmp allocates 128 virtual channels to handle NNAs. Using the SMIX API can also affect that number IIRC.

**Comment by Wohlstand** [comment]
I see, thanks for the note, but:

> xmp_module::chn—for IT modules

Is this valid for all other modules too? Which way is universal?

**Comment by AliceLR** [comment]
Ok, to rephrase: the correct field is `xmp_module::chn`.

For IT modules, and most likely for any module where SMIX has been enabled (not sure), `xmp_frame_info::virt_channels` is guaranteed to report the wrong number.

**Comment by sezero** [comment]
I think this can be closed now. If there are still unclear points or further questions, then re-open.

**Comment by Wohlstand** [comment]
Ye, it's fine to close, the question was solved a while ago.
