### ISSUE TITLE
Cannot play this xm

### ISSUE THREAD

**Issue by blue-devil** [libxmp/libxmp#604]
Hello folks.
Thank you for this awesome library. I can play all of my XM music with this library without problem. I have only one file that i cannot play.

You can download it from here:
https://gofile.io/d/nSDXHY

Interesting thing is i can play this XM file with old xmplay.exe(unforseen) application. That is why i open an issue. I cannot understand if the problem resides in XM file or in the library. 

Thank you.

**Comment by AliceLR** [comment]
Looks like the BPM is junk (512), as far as libxmp is concerned at least. I encountered this with another XM in #598 (`- unknown/rienne va plus.xm` on Modland).
```
Loading pentagram.xm (1 of 1)
xmp_load_module [src/load.c:353] path = pentagram.xm
xmp_load_module [src/load.c:370] decrunch
libxmp_decrunch [src/depackers/depacker.c:384] Not packed
load_module [src/load.c:250] load
load_module [src/load.c:255] test Fast Tracker II
load_module [src/load.c:259] load format: Fast Tracker II
xm_load [src/loaders/xm_load.c:826] bad tempo or BPM: 6 512
xmp_release_module [src/load.c:518] Freeing memory
xmp_release_module [src/load.c:567] free dirname/basename
```

**Comment by AliceLR** [comment]
Looks like yet another Modplug extension, great!

**Comment by sagamusix** [comment]
> Looks like yet another Modplug extension, great!

It is in fact a fully supported feature by FT2 itself, thanks to lack of header sanitiziation. Files with a default BPM higher than 255 will play perfectly in FT2.

**Comment by AliceLR** [comment]
> It is in fact a fully supported feature by FT2 itself, thanks to lack of header sanitiziation. Files with a default BPM higher than 255 will play perfectly in FT2.

Good to know. It turns out Digital Tracker and Protracker 3.6 have the same "feature"...

Liquid Tracker properly clamps BPM from input files. SoundFX doesn't even have BPM internally so higher values are *probably* intended or at least work.

**Comment by blue-devil** [comment]
Thank you guys it works like a charm
