### ISSUE TITLE
use of amiga/windows types in med.h and rtm_load.c

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#614]
Is there a point to using amiga / windows types in med.h and rtm_load.c?
https://github.com/libxmp/libxmp/blob/master/src/loaders/med.h#L13
https://github.com/libxmp/libxmp/blob/master/src/loaders/rtm_load.c#L26

Can't we convert to using libxmp types instead? [patch.txt](https://github.com/libxmp/libxmp/files/9579260/patch.txt)

**Comment by AliceLR** [comment]
In both cases I believe this is because the format documentation also uses them. I don't really see the need in replicating them down to the type names (especially given that it's easier to mistake WORD and DWORD than it is uint16 and uint32).

**Comment by sezero** [comment]
Should we patch, then?

**Comment by AliceLR** [comment]
I think it would be OK to get rid of those types, yes.
