### ISSUE TITLE
MOD file plays in slow motion?

### ISSUE THREAD

**Issue by HunterZ** [libxmp/libxmp#619]
UltraX.mod seems to play in slow motion, with a listed duration of almost 40 minutes: https://modarchive.org/index.php?request=view_by_moduleid&query=58591

This is definitely incorrect behavior.

Edit: Sorry, probably should've filed this against libxmp? Let me know if I need to re-file it over there.

**Comment by sezero** [comment]
@AliceLR: Any ideas?

**Comment by AliceLR** [comment]
This is unfortunately a duplicate of #505. Thanks for the reminder, because this really needs to be fixed.

**Comment by sagamusix** [comment]
I will close this duplicate issue. Feel free to subscribe to the related issue if you want to be notified of when this is fixed.
