### ISSUE TITLE
distutils package is deprecated and will be removed in Python 3.12

### ISSUE THREAD

**Issue by kmccurley** [libxmp/libxmp#621]
When I use python-xmp-toolkit installed with pip, I see a warning:
```
python3.10/site-packages/libxmp/version.py:39: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion
```
This may cause libxmp to break starting with python 3.12.

**Comment by sezero** [comment]
This doesn't seems to have anything to do with libxmp itself. You should possibly file an issue report at https://github.com/python-xmp-toolkit/python-xmp-toolkit
