### ISSUE TITLE
[Android] Some tune doesn't show row view

### ISSUE THREAD

**Issue by knight-ryu12** [libxmp/libxmp#63]
https://imgur.com/LHNF4bb

nagz xylan orb doesn't show row view,is there an restriction?

**Comment by knight-ryu12** [comment]
http://modarchive.org/index.php?request=view_by_moduleid&query=67892
Test case 1: xylan orb [short] by nagz.
Also there is another test case . but I forgot filename and such.

**Comment by LossyDragon** [comment]
I'm checking into this, but its failing at this line because **lineInPattern** is greater than **numRows**

https://github.com/cmatsuoka/xmp-android/blob/8a42a3327d76649d70a7c17c46e926e3275079c3/app/src/main/java/org/helllabs/android/xmp/player/viewer/PatternViewer.java#L178

**Comment by LossyDragon** [comment]
Update: It seems XMP cannot get the row information from this module. Checking it out in OpenMPT, each pattern contains 256 rows. While XMP reports 0.

**Comment by AliceLR** [comment]
Looks like the issue might come from [here](https://github.com/cmatsuoka/xmp-android/blob/8a42a3327d76649d70a7c17c46e926e3275079c3/app/src/main/jni/xmp-jni.c#L329). For some reason the JNI bindings `& 0xff` every value read from the `xmp_frame_info` struct, despite both `xmp_frame_info` and the destination buffer both being ints.

**Comment by LossyDragon** [comment]
> Looks like the issue might come from [here](https://github.com/cmatsuoka/xmp-android/blob/8a42a3327d76649d70a7c17c46e926e3275079c3/app/src/main/jni/xmp-jni.c#L329). For some reason the JNI bindings `& 0xff` every value read from the `xmp_frame_info` struct, despite the `xmp_frame_info` source values and the destination buffer both being ints.

You'd be correct on this 😅 
![PUTcHr2](https://user-images.githubusercontent.com/4994318/100332760-640be380-2f97-11eb-91ec-f21789975d91.png)

**Comment by LossyDragon** [comment]
I put up a PR for this issue in the android repository.

**Comment by LossyDragon** [comment]
I believe this can be closed as there is a pending fix over at the android repo. 

Unless there are more test cases to try?

**Comment by knight-ryu12** [comment]
Closing in favor of xmp-android#15
