### ISSUE TITLE
Static builds are not working with MSVC

### ISSUE THREAD

**Issue by dbarkar** [libxmp/libxmp#640]
According to this code from `xmp.h` 
```
#if defined(_WIN32) && !defined(__CYGWIN__)
# if defined(BUILDING_STATIC)
#  define LIBXMP_EXPORT
# elif defined(BUILDING_DLL)
#  define LIBXMP_EXPORT __declspec(dllexport)
# else
#  define LIBXMP_EXPORT __declspec(dllimport)
# endif
...
#endif
```
It's required for an end user to define `BUILDING_STATIC` before the inclusion of `xmp.h`.
Is it expected behavior?

It's a good practice to export such defines with CMake targets. I see that you add this define to the target `XMP_IF` but it isn't exported. 
I suggest:
1) Export `BUILDING_STATIC` with `xmp_static` target
2) Export `BUILDING_DLL` with `xmp_shared` target
3) Use more specific name to avoid name collisions, like `LIBXMP_STATIC` or so.

I'm happy to help with the issue if we are on the same page.

**Comment by sezero** [comment]
> It's required for an end user to define `BUILDING_STATIC` before the inclusion of `xmp.h`. Is it expected behavior?

Yes

> It's a good practice to export such defines with CMake targets. I see that you add this define to the target `XMP_IF` but it isn't exported. I suggest:
> 
>     1. Export `BUILDING_STATIC` with `xmp_static` target
> 
>     2. Export `BUILDING_DLL` with `xmp_shared` target
> 
>     3. Use more specific name to avoid name collisions, like `LIBXMP_STATIC` or so.
> 
> I'm happy to help with the issue if we are on the same page.

Patches are welcome. CC: @madebr

**Comment by madebr** [comment]
I think `BUILDING_DLL` is an artifact from autotools.
I don't know how to make `libtool` pass different macro's to shared and static libraries.

For CMake, adding these macro's with `INTERFACE` visibility would make the choice between shared/static libxmp library more transparent.

**Comment by sezero** [comment]
> I think `BUILDING_DLL` is an artifact from autotools.

It is: to trigger the dllexport in xmp.h

> I don't know how to make `libtool` pass different macro's to shared and static libraries.

libxmp doesn't use libtool at all
