### ISSUE TITLE
Issues in MASI16 loader

### ISSUE THREAD

**Issue by sagamusix** [libxmp/libxmp#647]
Just from a quick skim, there are several issues with the MASI16 loader:

- Channel panning is not imported
- Notes play at the wrong pitch
- No effect translation whatsoever, so any effects encountered in pattern data will do a completely different thing compared to what was intended (as a consequence there are lots of random pattern breaks)
- Probably more issues

As a consequence, most of these files play completely incorrectly: https://www.exotica.org.uk/mediawiki/index.php?title=Special%3AModland&md=search&mod=old&aut=&for=epic+megagames+masi&col=&siz=&ins=

In its current state, it would make more sense to disable this loader temporarily until those problems are addressed.

**Comment by AliceLR** [comment]
I suspect this loader was tested solely with the Silverball modules, which make far less use of effects. Almost all of the Epic Pinball modules are available in the newer MASI format, so IMO that isn't a good enough reason to disable this loader.

**Comment by sagamusix** [comment]
This should be good enough for the time being after merging #649.
