### ISSUE TITLE
Can't play mo3 modules.

### ISSUE THREAD

**Issue by RocketRide9** [libxmp/libxmp#658]
xmp failse to play mo3 files.
I'm using xmp from fedora 38 repos.
```
xmp *.mo3
Extended Module Player 4.1.0
Copyright (C) 1996-2016 Claudio Matsuoka and Hipolito Carraro Jr
Using PulseAudio sound output
Mixer set to 44100 Hz, 16bit, cubic spline interpolated stereo
Press 'h' for help

Loading hereyes_remake.mo3 (1 of 2)
xmp: hereyes_remake.mo3: Error depacking file

Loading ramagardens_remake.mo3 (2 of 2)
xmp: ramagardens_remake.mo3: Error depacking file

```
Modules i tried to play: https://api.modarchive.org/downloads.php?moduleid=155846#ramagardens_remake.mo3 https://api.modarchive.org/downloads.php?moduleid=155849#hereyes_remake.mo3

**Comment by AliceLR** [comment]
Right now libxmp's MO3 "support" requires that [unmo3](https://github.com/lclevy/unmo3) has been compiled and installed. There are plans to fix this, but I haven't got around to it yet :(

**Comment by sagamusix** [comment]
Should probably be closed in favor of https://github.com/libxmp/libxmp/issues/26
