### ISSUE TITLE
bogus -Warray-bounds warning in mmcmp.c?

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#667]
This appeared in mingw 32 bit (but not 64 bit) autotools builds:

```
In function 'block_unpack_8bit',
    inlined from 'decrunch_mmcmp' at src/depackers/mmcmp.c:441:8:
src/depackers/mmcmp.c:263:35: warning: array subscript 4294967295 is above array bounds of 'const uint32[8]' {aka 'const unsigned int[8]'} [-Warray-bounds=]
  263 |                 if (d >= cmd_8bits[numbits]) {
      |                          ~~~~~~~~~^~~~~~~~~
src/depackers/mmcmp.c: In function 'decrunch_mmcmp':
src/depackers/mmcmp.c:60:21: note: while referencing 'cmd_8bits'
   60 | static const uint32 cmd_8bits[8] = {
      |                     ^~~~~~~~~
In function 'block_unpack_16bit',
    inlined from 'decrunch_mmcmp' at src/depackers/mmcmp.c:435:8:
src/depackers/mmcmp.c:178:35: warning: array subscript 4294967295 is above array bounds of 'const uint32[16]' {aka 'const unsigned int[16]'} [-Warray-bounds=]
  178 |                 if (d >= cmd_16bit[numbits]) {
      |                          ~~~~~~~~~^~~~~~~~~
src/depackers/mmcmp.c: In function 'decrunch_mmcmp':
src/depackers/mmcmp.c:68:21: note: while referencing 'cmd_16bit'
CC src/depackers/s404_dec.lo
   68 | static const uint32 cmd_16bit[16] = {
      |                     ^~~~~~~~~
```

Looks bogus to me, but still wanted a second opinion. If it's bogus, feel free to close.

**Comment by AliceLR** [comment]
Yikes, looking into it. This might be bogus.

**Comment by sezero** [comment]
The gcc version in question seems to be 13.1 according to CI logs.

**Comment by AliceLR** [comment]
Oh, okay. I don't see this but I am still on GCC 12.2.0. Time to update MSYS2 and try again...

**Comment by AliceLR** [comment]
Yep, I can reproduce this now. It looks like a GCC bug.

**Comment by sezero** [comment]
Close this then, yes?

**Comment by AliceLR** [comment]
Not sure. It *might* be worth leaving open until GCC fixes it or until someone spots an issue (I do not think it exists though).

**Comment by sezero** [comment]
AFAIK, there are a few bogus `-Wundef` reports at gcc bugzilla. We need a reduced testcase to add another.

**Comment by sezero** [comment]
Is this about the same thing?
https://github.com/OpenMPT/openmpt/commit/1f186e868f375b695e689009868215713f1c4e4b

CC: @sagamusix

**Comment by AliceLR** [comment]
I don't think this is the same thing, since the OpenMPT patch is working around a `-Wstringop-truncation` warning (which we've patched a fair number of here too...). I'll take a look at mmcmp.c again *just in case* and see if there's anything we can do to trick it into shutting up :)

**Comment by AliceLR** [comment]
Still convinced this is a separate GCC bug. The *only* things that have shut it up:

* Clamping `numbits &= 7` before or after the statement `if (d >= cmd_8bits[numbits]) { ... } else { ... }` or `cmd_8bits[numbits & 7]`, but NOT at the end of the `if` branch of the statement. The compiler thinks this statement is capable of storing -1 into `numbits` somehow.
* Making `numbits` a `uint8` or `uint16`.

**Comment by sezero** [comment]
Make it an uint8 then? https://github.com/libxmp/libxmp/compare/master...sezero:libxmp:gcc13

**Comment by AliceLR** [comment]
That works for me.

**Comment by sezero** [comment]
OK will pull it in directly when its CI runs complete.

**Comment by sezero** [comment]
Fixed by https://github.com/libxmp/libxmp/commit/85df6a498ef06ab7189a38fb1c14c11b6f506b66

**Comment by sezero** [comment]
Opened a ticket at gcc bugzilla: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115005
