### ISSUE TITLE
fate of the lite package

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#670]
Now that the whole source is under MIT license, we should consider the
fate of the lite package: As I understand it, the lite package existed
because (i) it provided a minimum set of loaders, and (ii) none of those
loaders were LGPL but MIT licensed.

What options we have:

(1) Keep lite packaging exactly as it is.
    Downside: People want to configure and build the lite version from
    git tree but that's not possible. (See e.g. #596, #620, #564, #502..)

(2) Keep lite version not as a separate package but as part of the main
    tree, and add configuration options in autotools / cmake. The cmake
    configuration option should be easy. Autotools side may require some
    work. Standalone makefiles might require some surgery, though.
    Downside: Source package will be bigger.

(3) Just kill the lite option altogether, put it to rest. If I remember
    correctly, @cmatsuoka once proposed this (I cannot find the mail, so
    I may be wrong about that..)

Comments?

**Comment by AliceLR** [comment]
The lite package should continue to exist for people who want an absolute minimal configuration IMO. Making it an Autotools/CMake config option might be more friendly user-side but I don't know if a bunch of disruptive buildsystem changes make it worth it right now.

**Comment by cmatsuoka** [comment]
I agree with Alice, there are some cases of lite being integrated into Odroid games and it would be interesting to allow those to be updated to newer releases.

**Comment by sezero** [comment]
So: Keep it exactly as it always has been?

**Comment by sezero** [comment]
Closing in favor of #676 now.

**Comment by sezero** [comment]
@cmatsuoka , @AliceLR : Please see PR #721 which finalizes this long story
