### ISSUE TITLE
[Feature Request] PlaySID v2.2+ (AMIGA) sidtune support

### ISSUE THREAD

**Issue by jopadan** [libxmp/libxmp#675]
Examples at [modland.com Andy Vaisey PlaySID tunes](http://modland.com/pub/modules/PlaySID/Andy%20Vaisey/)
@erique's [playsid.library](https://github.com/erique/playsid.library)

**Comment by sagamusix** [comment]
This makes no sense to support at all in libxmp (and also not in libmodplug, where I see you created a similar request).

SID files are not tracked music. libxmp provides infrastructure to play and mix samples in pattern-based formats. A SID file does not contain any samples, nor does it contain pattern data. It contains binary code to be executed on a real or emulated CPU and a real or emulated SID chip. libxmp does not provide any CPU emulation and no SID emulation, nor should it. As a result, it doesn't make sense at at all to support SID music in a library like libxmp (that also includes libmodplug, libopenmpt, BASS, MilkyPlay and all the other players out there. They all work the same way internally). There are existing libraries that can play SID files perfectly, and in turn those libraries would be completely incapable of playing the formats that libxmp supports. Those two things are completely unrelated, and it makes no sense to mix them in the same library.
