### ISSUE TITLE
Is that possible to play a file that uses a vst plugin?

### ISSUE THREAD

**Issue by Lucas-Marcel** [libxmp/libxmp#680]
i'm not sure if that's possible, i found nothing related on the internet.

**Comment by sezero** [comment]
Don't know anything about vst plugins. @AliceLR ?

**Comment by Lucas-Marcel** [comment]
ohh i guess it would need a vst sdk to work.

**Comment by AliceLR** [comment]
libxmp does not support VSTs, and I don't think even libopenmpt does (just OpenMPT). Trying to support these would be a pain...
