### ISSUE TITLE
test_mixer_bidi_sync does not test all cases

### ISSUE THREAD

**Issue by neumatho** [libxmp/libxmp#681]
For the test_mixer_bidi_sync test, in function bidi_sync_test_mode(), the rate and interp is not used in the test. Instead are hardcoded values of 8000 and XMP_INTERP_SPLINE.

I guess this is an error and the arguments should be used?

-Thomas

**Comment by sezero** [comment]
Looks like it.

@AliceLR: The following OK? (Passes `make devcheck` locally)

```diff
diff --git a/test-dev/test_mixer_bidi_sync.c b/test-dev/test_mixer_bidi_sync.c
index 932493e..2a68b7d 100644
--- a/test-dev/test_mixer_bidi_sync.c
+++ b/test-dev/test_mixer_bidi_sync.c
@@ -23,8 +23,8 @@ static void bidi_sync_test_mode(xmp_context opaque, int rate, int interp, const
 	struct xmp_frame_info info;
 	int i, j;
 
-	xmp_start_player(opaque, 8000, XMP_FORMAT_MONO);
-	xmp_set_player(opaque, XMP_PLAYER_INTERP, XMP_INTERP_SPLINE);
+	xmp_start_player(opaque, rate, XMP_FORMAT_MONO);
+	xmp_set_player(opaque, interp, XMP_INTERP_SPLINE);
 
 	for (i = 0; i < RENDER_FRAMES; i++) {
 		xmp_play_frame(opaque);
```

**Comment by AliceLR** [comment]
> Looks like it.
> 
> @AliceLR: The following OK? (Passes `make devcheck` locally)
> 
> ```diff
> diff --git a/test-dev/test_mixer_bidi_sync.c b/test-dev/test_mixer_bidi_sync.c
> index 932493e..2a68b7d 100644
> --- a/test-dev/test_mixer_bidi_sync.c
> +++ b/test-dev/test_mixer_bidi_sync.c
> @@ -23,8 +23,8 @@ static void bidi_sync_test_mode(xmp_context opaque, int rate, int interp, const
>  	struct xmp_frame_info info;
>  	int i, j;
>  
> -	xmp_start_player(opaque, 8000, XMP_FORMAT_MONO);
> -	xmp_set_player(opaque, XMP_PLAYER_INTERP, XMP_INTERP_SPLINE);
> +	xmp_start_player(opaque, rate, XMP_FORMAT_MONO);
> +	xmp_set_player(opaque, interp, XMP_INTERP_SPLINE);
>  
>  	for (i = 0; i < RENDER_FRAMES; i++) {
>  		xmp_play_frame(opaque);
> ```

This seems fine. I don't know why it's like this, probably just an oversight. Please be sure to PR that patch so it goes through CI—I remember this test in particular being temperamental.
