### ISSUE TITLE
Maybe some issue with random panning variations

### ISSUE THREAD

**Issue by neumatho** [libxmp/libxmp#685]
Hi,

I have noticed that the Test_Storlek_20_Pan_Swing_And_Set_Pan unit test fails sometimes by randomness error, at least in my C# port of XmpLib. I have tried different random algorithms, but it keep fails occasionally.

I then tried to dive into the code on how this is calculated and found this.

In read_event.c file at line 1244, you have this block of code:

```
if (rvv) {
	CLAMP(rvv, 0, 64);
	xc->rpv = rand() % (rvv + 1) - (rvv / 2);
} else {
	xc->rpv = 0;
}
```

In the test, rvv is 64. So in cases, where _rand() % (rvv + 1)_ result in a value below 32, xc->rpv will be set to a negative number.

If we then look in player.c at line 1280, you have this block of code:

```
if (IS_PLAYER_MODE_IT()) {
	finalpan = finalpan + xc->rpv * 4;
}

CLAMP(finalpan, 0, 255);
```

finalpan is zero in the test, so it will result in a negative number by xc->rpv * 4. Then you have the CLAMP, which will set finalpan to zero. So if xc->rpv is set to different numbers, but all negative, the resulting will be zero making the unit test fail, because all values are 0.

I guess there is something wrong somewhere. Either xc->rpv should not be negative or maybe a +128 should be added somewhere. Do you have any idea what to fix or I am totally wrong here and everything is as it should be?

Thomas

**Comment by sezero** [comment]
Related:  #723

**Comment by AliceLR** [comment]
Any objections to replacing all `rand()` usage with our own xorshift* and/or format-specific functions? @cmatsuoka @sezero @sagamusix

**Comment by AliceLR** [comment]
> Either xc->rpv should not be negative

From my understanding, negative is correct here—this is random panning *variation* and if you removed negative numbers, it would be unable to vary the panning toward the left.

**Comment by sagamusix** [comment]
I'm not particularly a fan of `rand()` anyway. OpenMPT also implements its own randomness sources, which has the advantage of making the switch to a deterministic randomness source (for fuzzing) very easy.

**Comment by sezero** [comment]
> Any objections to replacing all `rand()` usage with our own xorshift* and/or format-specific random functions? This _might_ help but I suspect libxmp is _also_ doing something wrong here. @cmatsuoka @sezero @sagamusix
> 
> edit: Specifically, a custom random function would probably have nicer randomness properties and also be faster than the `idiv` limiting in this specific use. `rand()` is also non-reentrant.

No objections from me

**Comment by AliceLR** [comment]
The NetBSD failure comes from the random panning slide generated values being (-8, 32, 20, -7), resulting in final panning values of (0, 128, 80, 0). The instrument in question has a random panning slide range of ±64 (the maximum), though libxmp treats this as ±32 and quadruples the return value later. The generated values are all within the ±32 range.

In other words, I suspect this is absolutely correct and the test itself is wrong for excluding center panning from the allowed panning range for these notes.

**Comment by AliceLR** [comment]
Another insane thing this test is doing: attempting to enforce a standard deviation of >=10 on essentially two ranges of 4 data points and one range of 8 data points. The only reason this "worked" before was fixed `rand()` seeds.

**Comment by sezero** [comment]
BTW: Your rng patch https://github.com/AliceLR/libxmp/commit/2b3c05f19aa0f66d2ed2c5dd0ba91d6144a7d24b works for me locally on i686-linux.

**Comment by AliceLR** [comment]
@sagamusix is the OpenMPT behavior of pan swing as ±(value) correct? When I test in IT 2.14, a pan swing value of 1 produces random values in the range [0,1], same as libxmp currently does. The OpenMPT behavior seems more useful...

**Comment by sagamusix** [comment]
I'm not sure if I was aware of the difference; but given that the entire feature is a bout randomness, I doubt that there is any practical difference in having a symmetric or non-symmetric interval for this effect.

**Comment by sagamusix** [comment]
Regarding the edit: You can see the actual pan value in IT's F5 view; press PageUp once from the default view to see the numeric values.

**Comment by AliceLR** [comment]
> I'm not sure if I was aware of the difference; but given that the entire feature is about randomness, I doubt that there is any practical difference in having a symmetric or non-symmetric interval for this effect.

Right, I'm not sure anyone would notice the "difference" for this. The only reason I asked is because I wrote the brute forcer for storlek_20.it's random seed assuming ±64 was correct :) I will leave libxmp's current behavior as-is, then.
