### ISSUE TITLE
test_mixer_bidi_sync part 2

### ISSUE THREAD

**Issue by neumatho** [libxmp/libxmp#689]
Hi again,

Created a new issue. This is a reference to issue #681.

I just saw now, that you have replaced the wrong argument in xmp_set_player for interp. It is the last argument in the method call that should be replaced. I tried to make a new PR with this change, but when running the test it begin to fail on the first mixer test. Probably because it now uses the nearest instead of spline, which was hardcoded before.

So I don't know what is needed to fix it or if you still want the test.

**Comment by sezero** [comment]
Send a patch please?

**Comment by neumatho** [comment]
```
diff --git a/test-dev/test_mixer_bidi_sync.c b/test-dev/test_mixer_bidi_sync.c
index 2a68b7d8..620a1c92 100644
--- a/test-dev/test_mixer_bidi_sync.c
+++ b/test-dev/test_mixer_bidi_sync.c
@@ -24,7 +24,7 @@ static void bidi_sync_test_mode(xmp_context opaque, int rate, int interp, const
        int i, j;

        xmp_start_player(opaque, rate, XMP_FORMAT_MONO);
-       xmp_set_player(opaque, interp, XMP_INTERP_SPLINE);
+       xmp_set_player(opaque, XMP_PLAYER_INTERP, interp);

        for (i = 0; i < RENDER_FRAMES; i++) {
                xmp_play_frame(opaque);

```

**Comment by sezero** [comment]
@AliceLR: This is good yes?

**Comment by AliceLR** [comment]
Yes, sorry I missed that before.

**Comment by sezero** [comment]
Unfortunately this results in a failure with `make devcheck` :

```
test 563: test_mixer_bidi_sync: at test_mixer_bidi_sync.c:34: xm:nearest:8k: **fail**
```

**Comment by neumatho** [comment]
Yeah, that was the same result I got.
