### ISSUE TITLE
Memory leak with instrument extras

### ISSUE THREAD

**Issue by neumatho** [libxmp/libxmp#693]
MED and His Master's Noise format uses extras, more specific instrument extras. The needed structures are allocated in their *_new_instrument_extras(), but I cannot find anywhere where they are freed again.

So I think there is missing some release function, just like e.g. the *_release_channel_extras().

**Comment by AliceLR** [comment]
They are freed in `xmp_release_module`.

**Comment by neumatho** [comment]
Ok, I can see that. Totally missed it :-)
