### ISSUE TITLE
Cannot load Imago Orpheus module

### ISSUE THREAD

**Issue by neumatho** [libxmp/libxmp#697]
I have a Imago Orpheus module, where it fails to load (attached). It fails when trying to load instrument number 40 at position 0xbba71 in the file. It fails when validating the signature (IS10). When looking in the file, it seems that the next structures are smaller than usual.

However, if I skip the signature check, magically the next instrument is loaded correctly and then the whole module is loaded. MikMod can load the module and it seems that it has some extra check if the signature is 4 zeros. But I'm not sure, if that the correct way of doing it, because when looking in the file, it seems there is a lot of smaller instrument chunks.

Another thing is that bi-direction loop is not detected. This module uses it a lot, e.g. for sample 24 to 31. This can be detected on bit 1 in the sample flag. See MikMod, which support it.

[Leaving_All_Behind.zip](https://github.com/libxmp/libxmp/files/13196632/Leaving_All_Behind.zip)

**Comment by AliceLR** [comment]
I've implemented the missing sample flags and changed how this loader checks instrument and sample magic strings, patch incoming shortly.

**Comment by sezero** [comment]
>  However, if I skip the signature check, magically the next instrument is loaded correctly and then the whole module is loaded. MikMod can load the module and it seems that it has some extra check if the signature is 4 zeros.

Mikmod checks 'IS10' and 'IW10' but libxmp doesn't seem to check 'IW10'. I don't see where mikmod checks 4 zeroes in load_imf.c??

**Comment by AliceLR** [comment]
> I don't see where mikmod checks 4 zeroes in load_imf.c??

Line 577 in my local copy. I can't verify whether or not the comment is lying about the reason these occur, but it's a MikMod comment, so...

**Comment by sezero** [comment]
> > I don't see where mikmod checks 4 zeroes in load_imf.c??
> 
> Line 577 in my local copy.

Hm, missed that, sorry.. 

> I can't verify whether or not the comment is lying about the reason these occur, but it's a MikMod comment, so...

archive.org seems to have a copy of the tracker
