### ISSUE TITLE
ScreamTracker 2 modules cant be loaded

### ISSUE THREAD

**Issue by neumatho** [libxmp/libxmp#700]
Hi,

I found a couple of ScreamTracker 2 modules, which can't be recognized. It is because, they don't have the 0x1a byte in the header. If this check is removed, they load fine. You may consider to remove this check.

[putup.zip](https://github.com/libxmp/libxmp/files/13220323/putup.zip)

**Comment by sezero** [comment]
Indeed: That reserved field shouldn't be relied upon IMO (mikmod doesn't check it.) @AliceLR?

**Comment by AliceLR** [comment]
This is probably just an EOF intended for compatibility with the `type` command—some other formats also contain them. I'll go through my STMs tomorrow and see what I have, but this sounds reasonable. @sagamusix?

**Comment by sezero** [comment]
Openmpt has notes about it here: https://github.com/OpenMPT/openmpt/blob/master/soundlib/Load_stm.cpp#L74-L85

**Comment by AliceLR** [comment]
Yep, confirmed there are exactly two STM modules on Modland with `02` as the "EOF" byte. None of the other modules I have get this byte wrong.
