### ISSUE TITLE
UltraTracker speed problems

### ISSUE THREAD

**Issue by neumatho** [libxmp/libxmp#702]
In the UltraTracker module The Blessing.ult, the set the speed to 0x20 at position 27, pattern 25. This slows the playing down, since the effect handler think it is a BPM change (normally goes from 0x20-0xff). In this case, it should be threated as a speed change, since according to the official documentation, BPM starts from 0x30.

```
   F - Speed; [0-2F] - CIA speed
   ---------------------------------
   Adjusts the CIA speed of the song.
   6 is the default adjustment setting (125 BPM);

   F - Speed BPM [30 - FF] - BPM speed
   -----------------------------------
   Adjusts the BPM (beats per minute) speed of the song.
   Default is 7D = 125 BPM.

   At a CIA speed of 6, there are 6 ticks between 2 lines. The number 
   of ticks depends on the set BPM speed.
   
   For example:
   125BPM =  50 ticks per second 
   250BPM = 100 ticks per second
 ```

Maybe you should introduce a minBpm variable which can be set in a loader?

[The Blessing.zip](https://github.com/libxmp/libxmp/files/13258913/The.Blessing.zip)

**Comment by sezero** [comment]
@AliceLR ?
