### ISSUE TITLE
"sleeping waste" has broken PWM playback?

### ISSUE THREAD

**Issue by SergioFLS** [libxmp/libxmp#717]
Using current `master`, version 4.6.0 and Xmp for Android v4.12.0 (which reportedly uses libxmp 4.4.1).

When I play meo-sleeping_waste.mod (https://modarchive.org/module.php?68014) on openmpt123, there's a PWM effect on the fourth channel playing at around 41 seconds into the song. On the listed libxmp versions I've tried, the wave only seems to be a pulse wave that doesn't change.

**Comment by sezero** [comment]
CC: @AliceLR

**Comment by nwoeanhinnogaehr** [comment]
It's because the module changes samples without retriggering the note. Protracker 2 and 3 differ in the handling of this - what you are looking for is what Protracker 2 does. Personally I'd also like to see xmp support this. As far as I'm aware there are not any Protracker 3 modules that break when samples changes without retriggering are allowed, but I may be wrong.

**Comment by AliceLR** [comment]
As far as I can tell libxmp doesn't do much when playing MODs when an instrument number isn't accompanied by a note. It should be possible to support this when Protracker quirks are active (which libxmp applies to this module, but unfortunately the tracker ID routine is hit-or-miss for others).

As is typical with changing anything related to M.K. MODs I will need to gather some more data before patching this ):

**Comment by TheEssem** [comment]
Plenty of 4mat's Protracker modules have this issue, including but probably not limited to:
- back again.mod (https://modarchive.org/module.php?76215)
- 4mat-menu1.mod (albeit to a lesser extent) (https://modarchive.org/module.php?66427)
- velocity.mod (https://modarchive.org/module.php?65281)

**Comment by nwoeanhinnogaehr** [comment]
Interestingly I noticed that 4mat-menu1.mod is identified as Fast Tracker M.K., and my understanding is that this will disable Protracker quirks (certainly it disables EFx at least). A couple more affected mods which are identified as Protracker M.K.:

- http://modland.com/pub/modules/Protracker/Goto80/minipitt.mod (the whole thing sounds bad in xmp, but especially the arpeggios starting at position 14)
- http://modland.com/pub/modules/Protracker/Clawz/hotwires.mod (channel 4, position 3+)
- http://modland.com/pub/modules/Protracker/MC%20MP/happy%20new%20year%201993.mod (channel 1, position 2+)

By the way, there are also some mods, e.g. http://modland.com/pub/modules/Protracker/Maktone/sleepless%20nights!.mod which are identified as Fast Tracker M.K. but contain EFx effects, but maybe I should leave that for another issue :)

**Comment by AliceLR** [comment]
All of that would be due to the tracker ID routine, which usually does a good job and other times completely hallucinates things. M.K. MODs don't have any real tracker fingerprinting so the best libxmp can do is guess based on other things.

`EFx` should probably rule out Fast Tracker but also sometimes people would just put useless effects in old MODs to spell out "signatures" and similar, so who knows what a false positive on that check would break ([here](https://docs.google.com/spreadsheets/d/1a8O9WIjPe8FS3SgyudxFhYlglb7zJb0HpH7FnS0UDCM/edit) is an example of the cursed amount of work this routine can cause).

**Comment by AliceLR** [comment]
I have a work-in-progress patch which *seems* to have fixed playback for the cited modules. It is not ready to merge yet, but if you'd like to test it, it's here: https://github.com/libxmp/libxmp/compare/master...AliceLR:add-protracker-ins-swap

> Interestingly I noticed that 4mat-menu1.mod is identified as Fast Tracker M.K., and my understanding is that this will disable Protracker quirks (certainly it disables EFx at least).

libxmp was correct in this instance—that copy of anarchymenu01 was likely resaved in a different tracker (possibly Fast Tracker) which zeroed out the unused sample loops. The copy on Modland is IDed correctly as Protracker.

This seems to have been resolved, and that link now redirects to the same copy that is on Modland: https://modarchive.org/index.php?request=view_by_moduleid&query=77578

**Comment by nwoeanhinnogaehr** [comment]
Thanks for implementing this! I just tried it out on a few modules, and it seems to work quite well!

The only issue I noticed so far is that when EFx commands are combined with instrument switching, the result doesn't totally match ProTracker. I think maybe EFx isn't supposed to persist when the sample is swapped. Check out channel 4 on http://modland.com/pub/modules/Protracker/Emax/enjoy%20the%20silence.mod

Thanks again for this great patch. I'll continue testing throughout the week.

**Comment by AliceLR** [comment]
> The only issue I noticed so far is that when EFx commands are combined with instrument switching, the result doesn't totally match ProTracker. I think maybe EFx isn't supposed to persist when the sample is swapped. Check out channel 4 on http://modland.com/pub/modules/Protracker/Emax/enjoy%20the%20silence.mod

I checked Protracker and OpenMPT and EFx does persist when the sample is swapped. I *think* this is a bug in the implementation of invert loop but I don't know what exactly.

**Comment by AliceLR** [comment]
I went ahead and opened the pull request for this; feel free to post additional results/feedback in either place. I assume it will be merged sometime during the weekend (assuming there aren't unresolved issues).

**Comment by AliceLR** [comment]
I went ahead and merged the branch as-is, but feel free to keep testing and/or report any issues you find.
