### ISSUE TITLE
storlek_20.it test fails on NetBSD 9.2.

### ISSUE THREAD

**Issue by AliceLR** [libxmp/libxmp#723]
The test for storlek_20.it fails in my NetBSD 9.2 VM with the following message: `pan not left-biased`.

The pan values checked in MINGW64 are: 108 108 108 108 24 24 44 44.
The pan values checked in NetBSD 9.2 are: 0 0 128 128 80 80 0 0.

For this particular check, these values all need to be <128. I don't know if this is an issue with my environment or a real problem.

**Comment by sezero** [comment]
Can this be about char being unsigned by default or something? (shooting in the dark here)

**Comment by sezero** [comment]
> Can this be about char being unsigned by default or something? (shooting in the dark here)

I guess not. Built libxmp and test-dev with -funsigned-char on linux, just passes all tests

**Comment by neumatho** [comment]
Can it have something to do with issue #685 that I reported a while back?

**Comment by sezero** [comment]
Worth looking into.

**Comment by sezero** [comment]
Yes, #685 looks directly related, as far as I can see

**Comment by sezero** [comment]
Closing in favor of #685
