### ISSUE TITLE
MSVC C4310 warnings

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#797]
We hit two of these in MSVC builds through cmake: 

`loaders\sample.c(134,16): warning C4310: cast truncates constant value`
which is for `(char)0x80`:
```c
			*p += (char)0x80;	/* cast needed by MSVC++ */
```

... and:
`test-dev\test_string_adjustment.c(6,9): warning C4310: cast truncates constant value`
which is for `(char)128` (i.e. the same reason):
```c
char string[80] = { 'h', 'e', 'l', 'l', 'o', 1, 2, 30, 31, 127,
	(char)128, 'w', 'o', 'r', 'l', 'd', ' ', ' ', ' ', 0 };
```

Should we do something about them?

**Comment by AliceLR** [comment]
I don't understand the need for the first cast, so maybe it can be dropped (maybe it predates `p` being a `uint8`?).

Does something like `'\x80'` fix the second instance?

**Comment by sezero** [comment]
> I don't understand the need for the first cast, so maybe it can be dropped (maybe it predates `p` being a `uint8 *`?).

Maybe. I don't know the reason either.

Removing the cast, changing it to `(unsigned char)` fixes it

> 
> Does something like `'\x80'` fix the second instance?

Yes.

Should we apply the following? (Asking before making a PR.)

```diff
--- a/src/loaders/sample.c
+++ b/src/loaders/sample.c
@@ -133,3 +133,3 @@ static void convert_signal(uint8 *p, int l, int r)
 		for (; l--; p++)
-			*p += (char)0x80;	/* cast needed by MSVC++ */
+			*p += (unsigned char)0x80;
 	}
--- a/test-dev/test_string_adjustment.c
+++ b/test-dev/test_string_adjustment.c
@@ -5,3 +5,3 @@ TEST(test_string_adjustment)
 	char string[80] = { 'h', 'e', 'l', 'l', 'o', 1, 2, 30, 31, 127,
-		(char)128, 'w', 'o', 'r', 'l', 'd', ' ', ' ', ' ', 0 };
+		'\x80', 'w', 'o', 'r', 'l', 'd', ' ', ' ', ' ', 0 };
 
```

**Comment by AliceLR** [comment]
I think that patch is OK to PR.
