### ISSUE TITLE
Missing quotes in CMakeLists

### ISSUE THREAD

**Issue by Lecodeurenretard** [libxmp/libxmp#810]
When building I noticed some quotes are missing in [CMakeLists.txt](https://github.com/libxmp/libxmp/blob/master/CMakeLists.txt#L173) at line 173 replacing 
```CMake
LINK_FLAGS " -Wl,--version-script,${CMAKE_CURRENT_SOURCE_DIR}/libxmp.map")
``` 
by 
```CMake
LINK_FLAGS " -Wl,--version-script,\"${CMAKE_CURRENT_SOURCE_DIR}/libxmp.map\"")
```

would let path with spaces to be supported

**Comment by sezero** [comment]
I guess this is the same issue at https://github.com/libsdl-org/SDL_mixer/issues/649#issuecomment-2543336374 ?

@madebr :  Is the patch good? If it is, do you want to make a PR for it or should we apply ourselves?

**Comment by madebr** [comment]
The patch is good.
For reference, SDL does this using `target_link_options` and setting a `LINK_DEPENDS` option [here](https://github.com/libsdl-org/SDL_mixer/blob/d4eba31e4ac23a81fffad02e91b17dcb2449a2cb/cmake/PrivateSdlFunctions.cmake#L288-L298).

By using `target_link_options`, cmake will do the escaping for you.
